import hajjLesson9Cover from "../../assets/lesson_images/hajj_lesson9.png";

export const LESSON_HAJJ_09 = {
  id: "hajj-09",
  guide: "hajj",
  lessonNumber: 9,
  totalLessons: 16,
  title: "The Journey to Mina",
  blocks: [
    { type: "cover", image: hajjLesson9Cover, lessonBadge: "LESSON 9 OF 16", title: "The Journey to Mina", subtitle: "Understand what Mina is, why pilgrims travel there, and what the days in this sacred valley mean for Hajj.", readingMinutes: 8 },
    { type: "cardList", title: "After This Lesson You'll Understand", cards: [
      { id: "c1", icon: "Question", label: "Why Mina is an essential part of Hajj." },
      { id: "c2", icon: "Heart", label: "What pilgrims do during their time in Mina." },
      { id: "c3", icon: "MoonStars", label: "The significance of spending the night in Mina on the 8th of Dhul Hijjah." },
      { id: "c4", icon: "BookOpen", label: "How to approach the journey with patience and intention." },
    ]},
    { type: "narrativeText", title: "Overview", icon: "BookOpen", paragraphs: [
      "Mina is a valley approximately five kilometres from Masjid al-Haram. It is called 'the City of Tents' because during the days of Hajj, it becomes one of the largest tent cities in the world, housing millions of pilgrims.",
      "On the 8th of Dhul Hijjah—known as Yawm at-Tarwiyah (the Day of Watering)—pilgrims travel from Makkah to Mina, where they spend the night in preparation for the Day of Arafah.",
    ]},
    { type: "narrativeText", title: "Why Mina Matters", icon: "Heart", paragraphs: [
      "Mina is where pilgrims will later cast stones at the three Jamarat pillars, commemorating Prophet Ibrahim's (AS) rejection of Shaytan's attempts to dissuade him from obeying Allah's command.",
      "Spending the night in Mina on the 8th of Dhul Hijjah is Sunnah. It prepares the pilgrim—physically and spiritually—for the greatest day of Hajj: the standing at Arafah.",
    ]},
    { type: "narrativeText", title: "The Days in Mina", icon: "Star", paragraphs: [
      "Pilgrims will return to Mina after Arafah and Muzdalifah on the 10th of Dhul Hijjah (Eid day) to begin the stoning of the Jamarat. They remain in Mina for the Tashreeq days—the 11th and 12th (or 13th for those who stay).",
      "The combination of these days makes Mina central to the Hajj experience. From the first night on the 8th to the final stoning before departure, Mina is a home base for the acts of pilgrimage.",
    ]},
    { type: "narrativeText", title: "Living Simply in Mina", icon: "MoonStars", paragraphs: [
      "In Mina, pilgrims live in large shared tents. The conditions are simple: shared sleeping space, basic facilities, and crowds. This simplicity is part of Hajj.",
      "Scholars encourage pilgrims to embrace this simplicity with gratitude. The Prophet ﷺ lived simply during Hajj and encouraged his companions to maintain their character and patience throughout. The discomfort of Mina is not a problem to be solved—it is part of the journey.",
    ]},
    { type: "numberedSteps", title: "The 8th of Dhul Hijjah", steps: [
      { heading: "Make Intention for Hajj", body: "If you have not yet entered Ihram, do so before travelling to Mina. Renew your intention for Hajj with the words: 'Labbayk Allahumma Hajjan.'" },
      { heading: "Travel to Mina", body: "Travel to Mina on the 8th of Dhul Hijjah after Fajr. The journey is made on foot, by bus, or via the Hajj transport system." },
      { heading: "Pray in Mina", body: "Spend the night in Mina and pray all five prayers there. Dhuhr, Asr, Maghrib, Isha, and Fajr are all shortened (qasr) in Mina but not combined." },
      { heading: "Occupy Your Time with Worship", body: "Use your time in Mina for dhikr, recitation of Qur'an, du'a, and learning. Avoid idle talk and arguments. This time is preparation for Arafah." },
      { heading: "Depart for Arafah After Fajr", body: "On the 9th of Dhul Hijjah, after Fajr prayer, depart for Arafah. The Day of Arafah begins. This is the most important day of Hajj." },
    ]},
    { type: "cardList", title: "Things to Remember", cards: [
      { id: "t1", icon: "Star", label: "Travel to Mina on the 8th of Dhul Hijjah (Yawm at-Tarwiyah)." },
      { id: "t2", icon: "Heart", label: "Spending the night in Mina on the 8th is Sunnah." },
      { id: "t3", icon: "MoonStars", label: "Prayers in Mina are shortened (qasr) but not combined." },
      { id: "t4", icon: "Question", label: "Mina is central to Hajj—pilgrims return here multiple times." },
      { id: "t5", icon: "BookOpen", label: "Live simply; embrace the conditions with patience." },
      { id: "t6", icon: "ListChecks", label: "The stoning of the Jamarat occurs in Mina on Eid and the Tashreeq days." },
      { id: "t7", icon: "Star", label: "Depart for Arafah after Fajr on the 9th." },
    ]},
    { type: "cardList", title: "Key Takeaways", cards: [
      { id: "k1", icon: "Star", label: "Mina is the tent city where pilgrims gather before and after Arafah." },
      { id: "k2", icon: "Heart", label: "The 8th of Dhul Hijjah in Mina is spiritual preparation for Arafah." },
      { id: "k3", icon: "BookOpen", label: "Simplicity, patience, and worship define time in Mina." },
      { id: "k4", icon: "Question", label: "Prayers are shortened in Mina." },
      { id: "k5", icon: "MoonStars", label: "The stoning of the Jamarat connects pilgrims to Ibrahim's legacy." },
    ]},
    { type: "insight", title: "A Moment to Notice", text: "Millions of pilgrims live side by side in Mina's tents—from every country, every background. The simplicity of the space strips away difference. In Mina, everyone is a pilgrim. Nothing more, nothing less." },
    { type: "insight", title: "Insight", text: "The Prophet ﷺ made Hajj only once, yet he described the Day of Arafah as the heart of it. Every journey to Mina is a step toward that heart. Use these hours not to worry about what comes next, but to prepare the place inside you that Arafah will meet." },
    { type: "insight", title: "Reflection", text: "When you imagine living simply in a tent for several days, what comes to mind? What would become important, and what would fall away?" },
    { type: "cardList", title: "Practice", cards: [
      { id: "p1", icon: "Star", label: "Learn the schedule of Hajj days: 8th in Mina, 9th in Arafah, nights in Muzdalifah, 10th onward back in Mina." },
      { id: "p2", icon: "Heart", label: "Understand the rule of qasr: shortening Dhuhr, Asr, and Isha to two rak'ahs each." },
      { id: "p3", icon: "BookOpen", label: "Read about the Jamarat and the story of Ibrahim (AS) rejecting Shaytan." },
      { id: "p4", icon: "MoonStars", label: "Prepare dhikr and du'as to use during your time in Mina." },
      { id: "p5", icon: "Question", label: "Reflect on what it means to live simply for the sake of Allah." },
      { id: "p6", icon: "ListChecks", label: "Review your Hajj itinerary so you know which day you travel, where, and when." },
    ]},
    { type: "qaCardList", title: "Common Questions", cards: [
      { id: "q1", question: "When do pilgrims travel to Mina?", answer: "On the 8th of Dhul Hijjah, known as Yawm at-Tarwiyah (the Day of Watering), after Fajr prayer." },
      { id: "q2", question: "Is staying in Mina on the 8th obligatory?", answer: "It is Sunnah, not obligatory. However, following the Sunnah of the Prophet ﷺ in Hajj is strongly encouraged." },
      { id: "q3", question: "How are prayers performed in Mina?", answer: "Prayers are shortened (qasr): Dhuhr, Asr, and Isha are prayed as two rak'ahs each. They are not combined." },
      { id: "q4", question: "What is Yawm at-Tarwiyah?", answer: "It is the 8th of Dhul Hijjah, the day pilgrims travel to Mina to begin the main rites of Hajj." },
      { id: "q5", question: "How long do pilgrims stay in Mina in total?", answer: "Pilgrims spend the night of the 8th in Mina, then return on Eid (10th) and remain for the Tashreeq days (11th, 12th, and optionally 13th)." },
      { id: "q6", question: "What are the Jamarat?", answer: "The Jamarat are three stone pillars in Mina representing the spots where Shaytan appeared to Prophet Ibrahim (AS). Pilgrims cast stones at them to commemorate Ibrahim's rejection of Shaytan." },
      { id: "q7", question: "What should I do with my time in Mina on the 8th?", answer: "Fill your time with dhikr, recitation of Qur'an, du'a, and learning. Use it as spiritual preparation for the Day of Arafah." },
      { id: "q8", question: "Is the journey to Mina on foot or by transport?", answer: "Both. Many pilgrims walk, and a Hajj transport system (buses and trains) connects Makkah to Mina, Arafah, and Muzdalifah." },
      { id: "q9", question: "What are the Tashreeq days?", answer: "The 11th, 12th, and 13th of Dhul Hijjah. Pilgrims remain in Mina and cast stones at the Jamarat during these days." },
      { id: "q10", question: "Can I leave Mina on the 12th?", answer: "Yes. Leaving Mina by sunset on the 12th is permissible. If you remain past sunset, you must stay for the 13th and cast stones that day as well." },
      { id: "q11", question: "What is it like in Mina?", answer: "Mina hosts millions of pilgrims in large shared tents. Conditions are simple and crowded. Patience and a spirit of gratitude are essential." },
      { id: "q12", question: "What happens after the night in Mina on the 8th?", answer: "After Fajr on the 9th, pilgrims depart for Arafah for the most important day of Hajj: the standing (Wuquf)." },
    ]},
    { type: "narrativeText", title: "Scholar Notes", icon: "BookOpen", paragraphs: [
      "Classical scholars agreed that spending the night of the 8th of Dhul Hijjah in Mina is Sunnah and was the practice of the Prophet ﷺ during his Farewell Pilgrimage.",
      "Scholars such as Imam an-Nawawi noted that the shortening of prayers in Mina is based on the authentic Sunnah, and that pilgrims should avoid combining prayers there unless they are also traveling.",
    ]},
    { type: "narrativeText", title: "References", icon: "BookOpen", paragraphs: [
      "Qur'an — Surah Al-Baqarah (2:198–203)",
      "Qur'an — Surah Al-Hajj (22:26–29)",
      "Hadith — Sahih al-Bukhari, Book of Hajj",
      "Hadith — Sahih Muslim, Book of Hajj (description of the Prophet's ﷺ Farewell Pilgrimage)",
      "Classical Scholarship — Imam an-Nawawi, Al-Majmu'; Ibn Qudamah, Al-Mughni",
      "Contemporary Guidance — Saudi Ministry of Hajj & Umrah; General Authority for the Care of the Two Holy Mosques",
    ]},
    { type: "insight", title: "My Notes Prompt", icon: "NotePencil", text: "Imagine spending your first night in Mina — in a tent, surrounded by millions of pilgrims from every part of the world. What would you want to remember about that night? What would you pray for before sleeping?" },
  ],
};
