import hajjLesson3Cover from "../../assets/lesson_images/hajj_lesson3.png";

export const LESSON_HAJJ_03 = {
  id: "hajj-03",
  guide: "hajj",
  lessonNumber: 3,
  totalLessons: 16,
  title: "Entering Ihram",
  blocks: [
    { type: "cover", image: hajjLesson3Cover, lessonBadge: "LESSON 3 OF 16", title: "Entering Ihram", subtitle: "Learn what it means to enter the sacred state of Ihram and begin your Hajj with sincerity, humility, and intention.", readingMinutes: 7 },
    { type: "cardList", title: "After This Lesson You'll Understand", cards: [
      { id: "c1", icon: "Question", label: "What Ihram is and why Muslims enter it." },
      { id: "c2", icon: "MoonStars", label: "Where pilgrims enter Ihram." },
      { id: "c3", icon: "BookOpen", label: "The practical steps before entering Ihram." },
      { id: "c4", icon: "Star", label: "What changes once the sacred state begins." },
      { id: "c5", icon: "Heart", label: "The restrictions observed while in Ihram." },
    ]},
    { type: "narrativeText", title: "Overview", icon: "BookOpen", paragraphs: [
      "Ihram is the sacred state that marks the beginning of Hajj. It is not simply a set of garments, but a state of worship entered with intention (niyyah) and the Talbiyah.",
      "From this moment forward, the pilgrim begins setting aside ordinary routines to focus wholeheartedly on Allah. The simplicity of Ihram reminds every pilgrim that, before Allah, all people stand equal.",
    ]},
    { type: "narrativeText", title: "Why it Matters", icon: "Heart", paragraphs: [
      "The first visible act of Hajj is not walking around the Ka'bah. It is making the conscious decision to leave behind status, comfort, and worldly distinctions.",
      "Millions of pilgrims wear simple garments, speak the same Talbiyah, and begin the same journey together. Ihram is a reminder that the pilgrimage is not about who we are in this world, but who we are before Allah.",
    ]},
    { type: "narrativeText", title: "Historical Context", icon: "BookOpen", paragraphs: [
      "The Prophet Muhammad ﷺ entered Ihram before beginning his pilgrimage and carefully observed its rulings throughout Hajj. His example established the practice followed by pilgrims to this day.",
    ]},
    { type: "narrativeText", title: "Preparing for Ihram", icon: "ListChecks", paragraphs: [
      "Before entering Ihram, renew your intention sincerely for Hajj. If possible, perform a ritual bath; this is a recommended act that helps prepare both body and mind for worship.",
      "Men wear the two simple white, unstitched cloths traditionally used for Ihram and avoid clothing tailored to fit the body. Women wear modest Islamic clothing that fulfills the requirements of hijab; there is no prescribed color, and ordinary modest dress is acceptable.",
      "Pilgrims enter Ihram before crossing the designated Miqat assigned to their route. Once the intention is made and the Talbiyah begins, the state of Ihram has started.",
    ]},
    { type: "narrativeText", title: "The Restrictions of Ihram", icon: "Question", paragraphs: [
      "While in Ihram, pilgrims avoid certain actions, including cutting hair or nails, applying perfume after entering Ihram, hunting land animals, marital relations, and actions that conflict with the dignity and purpose of the pilgrimage.",
      "These restrictions encourage mindfulness, discipline, and devotion.",
    ]},
    { type: "numberedSteps", title: "Step-by-Step", steps: [
      { heading: "Renew Your Intention", body: "Begin with sincerity. Remember that Allah knows what is in every heart and that the purpose of Ihram is worship." },
      { heading: "Perform Ghusl", body: "Prepare body and mind. If possible, perform the recommended ritual bath before entering Ihram." },
      { heading: "Dress Appropriately", body: "Understand what the garments represent. Men wear the two simple white, unstitched cloths. Women wear modest Islamic clothing that fulfills the requirements of hijab." },
      { heading: "Know Your Miqat", body: "Know the boundary for your route. Pilgrims must enter Ihram before crossing the designated Miqat assigned to their route." },
      { heading: "Begin the Sacred State", body: "Make the intention and begin the Talbiyah. Once the intention is made and the Talbiyah begins, the state of Ihram has started." },
      { heading: "Review the Restrictions", body: "Know what changes during Ihram. Learning the restrictions before travelling allows you to enter the sacred state with confidence and avoid preventable mistakes." },
    ]},
    { type: "cardList", title: "Things to Remember", cards: [
      { id: "t1", icon: "Heart", label: "Ihram is a sacred state—not simply special clothing." },
      { id: "t2", icon: "Star", label: "Begin with a sincere intention." },
      { id: "t3", icon: "BookOpen", label: "Perform ghusl if possible as a recommended preparation." },
      { id: "t4", icon: "Question", label: "Know your Miqat before travelling." },
      { id: "t5", icon: "ListChecks", label: "Enter Ihram before crossing the Miqat." },
      { id: "t6", icon: "MoonStars", label: "Once intention and Talbiyah begin, the sacred state has started." },
      { id: "t7", icon: "Question", label: "Learn the restrictions before travelling." },
      { id: "t8", icon: "Heart", label: "Remember Allah often." },
      { id: "t9", icon: "Star", label: "The clothing is an outward symbol; the spiritual state is central." },
    ]},
    { type: "cardList", title: "Key Takeaways", cards: [
      { id: "k1", icon: "Star", label: "Ihram marks the beginning of Hajj." },
      { id: "k2", icon: "MoonStars", label: "It begins with intention and the Talbiyah." },
      { id: "k3", icon: "Heart", label: "The clothing symbolizes humility and equality." },
      { id: "k4", icon: "BookOpen", label: "The Miqat is the designated boundary for entering Ihram." },
      { id: "k5", icon: "Question", label: "The restrictions help cultivate focus and self-discipline." },
      { id: "k6", icon: "ListChecks", label: "Preparing beforehand makes entering Ihram more confident and peaceful." },
      { id: "k7", icon: "Heart", label: "Ihram is about the state of worship, not simply what you wear." },
    ]},
    { type: "insight", title: "Insight", text: "Two pieces of simple white cloth have become one of the most recognizable symbols of Hajj. Yet their purpose is not to make everyone look the same. Their purpose is to help everyone remember the same truth: before Allah, every pilgrim stands equal—whether a ruler or a laborer, wealthy or poor. The heart, not the clothing, is what truly distinguishes a believer." },
    { type: "cardList", title: "Practice", cards: [
      { id: "p1", icon: "Question", label: "Learn your Miqat location." },
      { id: "p2", icon: "MoonStars", label: "Practice putting on Ihram garments if you are a man." },
      { id: "p3", icon: "BookOpen", label: "Review the restrictions of Ihram." },
      { id: "p4", icon: "Heart", label: "Prepare your intention before the day of departure." },
      { id: "p5", icon: "ListChecks", label: "Make a simple checklist for your Ihram preparations." },
      { id: "p6", icon: "Star", label: "Read through the restrictions again shortly before travelling so they are familiar when the moment arrives." },
    ]},
    { type: "qaCardList", title: "Common Questions", cards: [
      { id: "q1", question: "Is Ihram only the clothing?", answer: "No. The clothing is one outward part of Ihram. The sacred state itself begins with intention and the Talbiyah." },
      { id: "q2", question: "Can I change my Ihram garments?", answer: "Yes. You may change into clean Ihram garments if needed while remaining in the state of Ihram." },
      { id: "q3", question: "When do the restrictions begin?", answer: "They begin once you have entered the state of Ihram through your intention and the Talbiyah." },
      { id: "q4", question: "Do women have to wear white for Ihram?", answer: "No. Women wear modest Islamic clothing that fulfills the requirements of hijab. There is no prescribed color." },
      { id: "q5", question: "What do men wear for Ihram?", answer: "Men wear the two simple white, unstitched cloths traditionally used for Ihram and avoid clothing tailored to fit the body." },
      { id: "q6", question: "Do women wear the same Ihram garments as men?", answer: "No. Women's Ihram is ordinary modest Islamic clothing that fulfills the requirements of hijab." },
      { id: "q7", question: "What is the Miqat?", answer: "The Miqat is the designated boundary assigned to a pilgrim's route before which the pilgrim enters Ihram." },
      { id: "q8", question: "Can I cross the Miqat before entering Ihram?", answer: "Pilgrims enter Ihram before crossing the designated Miqat assigned to their route." },
      { id: "q9", question: "Is ghusl required before Ihram?", answer: "Performing a ritual bath is described as a recommended act that helps prepare the body and mind for worship." },
      { id: "q10", question: "Why is Ihram important beyond the clothing?", answer: "The sacred state is a conscious decision to set aside ordinary routines and focus wholeheartedly on Allah." },
      { id: "q11", question: "What restrictions should I learn before travelling?", answer: "Cutting hair or nails, applying perfume after entering Ihram, hunting land animals, marital relations, and actions that conflict with the dignity and purpose of the pilgrimage." },
      { id: "q12", question: "Can I prepare for Ihram before I reach the Miqat?", answer: "Yes. You can prepare beforehand—learning your Miqat, practicing garments, reviewing restrictions, and preparing your intention—while the actual state begins with intention and Talbiyah before crossing the Miqat." },
    ]},
    { type: "narrativeText", title: "Scholar Notes", icon: "BookOpen", paragraphs: [
      "Many first-time pilgrims focus almost entirely on wearing the correct clothing. While this is important, scholars consistently emphasize that the spiritual state of humility, sincerity, and remembrance is the true essence of Ihram.",
      "The garments are an outward symbol of an inward commitment. Learning the restrictions beforehand helps the pilgrim enter this state with confidence and peace of mind.",
    ]},
    { type: "narrativeText", title: "References", icon: "BookOpen", paragraphs: [
      "Qur'an — Surah Al-Baqarah (2:196–197)",
      "Qur'an — Surah Al-Hajj (22:27–29)",
      "Hadith — Sahih al-Bukhari, Book of Hajj",
      "Hadith — Sahih Muslim, Book of Hajj",
      "Classical Scholarship — Imam an-Nawawi; Ibn Qudamah; Ibn Hajar al-'Asqalani",
      "Contemporary Guidance — Saudi Ministry of Hajj & Umrah; General Authority for the Care of the Two Holy Mosques",
    ]},
  ],
};
