import hajjLesson7Cover from "../../assets/lesson_images/hajj_lesson7.png";

export const LESSON_HAJJ_07 = {
  id: "hajj-07",
  guide: "hajj",
  lessonNumber: 7,
  totalLessons: 16,
  title: "Tawaf",
  blocks: [
    { type: "cover", image: hajjLesson7Cover, lessonBadge: "LESSON 7 OF 16", title: "Tawaf", subtitle: "Learn the meaning, purpose, and sequence of Tawaf—the act of circling the Ka'bah in worship of Allah.", readingMinutes: 9 },
    { type: "cardList", title: "After This Lesson You'll Understand", cards: [
      { id: "c1", icon: "Question", label: "What Tawaf is and why it is performed." },
      { id: "c2", icon: "Heart", label: "The spiritual significance of circling the Ka'bah seven times." },
      { id: "c3", icon: "MoonStars", label: "The correct sequence and key points to observe during Tawaf." },
      { id: "c4", icon: "BookOpen", label: "What Idtiba' and Ramal are and when they apply." },
      { id: "c5", icon: "Star", label: "Common errors pilgrims make and how to avoid them." },
      { id: "c6", icon: "ListChecks", label: "What follows immediately after Tawaf." },
    ]},
    { type: "narrativeText", title: "Overview", icon: "BookOpen", paragraphs: [
      "Tawaf is the act of circumambulating the Ka'bah seven times in a counterclockwise direction. It is one of the most significant acts of worship in both Hajj and Umrah, and it begins and ends at the Black Stone (al-Hajar al-Aswad).",
      "The Ka'bah stands at the center of Masjid al-Haram, and Tawaf takes place on the open marble floor surrounding it. At any hour of the day or night, pilgrims circle the Sacred House, filling the air with dhikr and du'a.",
    ]},
    { type: "narrativeText", title: "Why it Matters", icon: "Heart", paragraphs: [
      "Tawaf is an act of pure worship: you are moving around the House of Allah, declaring His greatness with each step. Every circuit is an expression of tawhid—the oneness of Allah—as countless believers circle in unison.",
      "The movement itself carries meaning. Just as the planets orbit and the angels circle the Throne of Allah in worship, the pilgrim joins this cosmic act of devotion, returning to the center of faith with every step.",
    ]},
    { type: "narrativeText", title: "Idtiba' and Ramal", icon: "BookOpen", paragraphs: [
      "For male pilgrims performing Tawaf al-Qudum (the arrival Tawaf), two special acts are observed. Idtiba' means draping the upper sheet of the Ihram under the right arm and over the left shoulder, leaving the right shoulder uncovered throughout all seven circuits.",
      "Ramal refers to walking briskly with short steps during the first three of the seven circuits. Both Idtiba' and Ramal apply only to male pilgrims and only during Tawaf al-Qudum. They are not required in other Tawafs.",
    ]},
    { type: "narrativeText", title: "The Black Stone", icon: "Star", paragraphs: [
      "Each circuit of Tawaf begins and ends at the Black Stone. If possible, the pilgrim touches and kisses it. If the crowd makes this difficult, pointing toward the stone while saying 'Allahu Akbar' is sufficient.",
      "The Prophet ﷺ said: 'The Black Stone came down from Paradise.' Touching or acknowledging it is an act of following the Sunnah, not a ritual that carries any independent spiritual power.",
    ]},
    { type: "narrativeText", title: "Du'a During Tawaf", icon: "MoonStars", paragraphs: [
      "There is no specific mandatory du'a for each circuit of Tawaf. The pilgrim is free to make any supplication in any language, engaging their heart fully with Allah.",
      "The exception is the du'a between the Yemeni Corner and the Black Stone, where it is recommended to say: 'Rabbana atina fi'd-dunya hasanah, wa fi'l-akhirati hasanah, wa qina 'adhab an-nar.'",
    ]},
    { type: "numberedSteps", title: "How to Perform Tawaf", steps: [
      { heading: "Enter with the Right Foot", body: "Enter Masjid al-Haram with your right foot, saying 'Bismillah, Allahumma salli 'ala Muhammad. Allahumma iftah li abwaba rahmatik.' Begin at the Black Stone." },
      { heading: "Make Your Intention", body: "State your intention to perform Tawaf. For male pilgrims doing Tawaf al-Qudum, apply Idtiba' now—drape your Ihram under the right arm." },
      { heading: "Begin at the Black Stone", body: "Face the Black Stone and say 'Allahu Akbar.' Touch or kiss it if possible; otherwise point toward it. This marks the start of your first circuit." },
      { heading: "Circle Counterclockwise", body: "Walk counterclockwise, keeping the Ka'bah on your left. For male pilgrims in Tawaf al-Qudum, perform Ramal (brisk walking) in the first three circuits." },
      { heading: "Acknowledge the Yemeni Corner", body: "Touch the Yemeni Corner with your right hand if possible. Between the Yemeni Corner and the Black Stone, recite: 'Rabbana atina fi'd-dunya hasanah wa fi'l-akhirati hasanah wa qina 'adhab an-nar.'" },
      { heading: "Complete Seven Circuits", body: "Complete seven full circuits, each beginning and ending at the Black Stone. Each time you pass it, say 'Allahu Akbar' and acknowledge it as above." },
    ]},
    { type: "cardList", title: "Things to Remember", cards: [
      { id: "t1", icon: "Star", label: "Tawaf consists of seven circuits, counterclockwise." },
      { id: "t2", icon: "Heart", label: "Each circuit begins and ends at the Black Stone." },
      { id: "t3", icon: "MoonStars", label: "Be in a state of Wudu throughout Tawaf." },
      { id: "t4", icon: "Question", label: "Point to the Black Stone if you cannot touch it." },
      { id: "t5", icon: "BookOpen", label: "Idtiba' and Ramal apply only to men in Tawaf al-Qudum." },
      { id: "t6", icon: "Star", label: "No specific du'a is required for each circuit." },
      { id: "t7", icon: "ListChecks", label: "Recite the Yemeni Corner du'a between the two corners." },
      { id: "t8", icon: "Heart", label: "Maintain remembrance and supplication throughout." },
      { id: "t9", icon: "Question", label: "Two rak'ahs of prayer follow Tawaf at Maqam Ibrahim." },
    ]},
    { type: "cardList", title: "Key Takeaways", cards: [
      { id: "k1", icon: "Star", label: "Tawaf is a central act of worship in Hajj and Umrah." },
      { id: "k2", icon: "Heart", label: "It expresses tawhid through unified movement around Allah's House." },
      { id: "k3", icon: "MoonStars", label: "Wudu is required; Ramal and Idtiba' are for men in Tawaf al-Qudum." },
      { id: "k4", icon: "BookOpen", label: "The Black Stone marks the start and end of each circuit." },
      { id: "k5", icon: "Question", label: "Two rak'ahs are prayed behind Maqam Ibrahim after Tawaf." },
      { id: "k6", icon: "ListChecks", label: "Sa'i begins after the post-Tawaf prayer." },
      { id: "k7", icon: "Star", label: "Every step in Tawaf is an act of worship directed to Allah alone." },
    ]},
    { type: "insight", title: "A Moment to Notice", text: "As you circle the Ka'bah, notice how every pilgrim around you—regardless of language, nation, or background—is moving in the same direction, making the same motion, calling upon the same Lord. Tawaf makes visible what faith holds invisibly: that all believers are united." },
    { type: "insight", title: "Insight", text: "Scholars explain that Tawaf has no beginning and no end except the one we mark. The Ka'bah has always been there. The circles continue. What changes is the pilgrim who arrives, walks, and carries something of this place back into the world." },
    { type: "insight", title: "Reflection", text: "If Tawaf is a form of du'a in motion, what would you want to say to Allah with each step you take?" },
    { type: "cardList", title: "Practice", cards: [
      { id: "p1", icon: "Star", label: "Memorise the du'a for between the Yemeni Corner and the Black Stone." },
      { id: "p2", icon: "Heart", label: "Learn the conditions of Tawaf: Wudu, correct direction, correct number of circuits." },
      { id: "p3", icon: "BookOpen", label: "Read about the significance of the Black Stone and the Yemeni Corner." },
      { id: "p4", icon: "MoonStars", label: "Visualise yourself completing all seven circuits with focus and presence." },
      { id: "p5", icon: "Question", label: "Understand what follows Tawaf: the two rak'ahs and then Sa'i." },
      { id: "p6", icon: "ListChecks", label: "Review the rules of Idtiba' and Ramal if you are a male pilgrim." },
      { id: "p7", icon: "Star", label: "Prepare a personal du'a you would want to make during your circuits." },
      { id: "p8", icon: "Heart", label: "Reflect on what tawhid—the oneness of Allah—means to you personally." },
    ]},
    { type: "qaCardList", title: "Common Questions", cards: [
      { id: "q1", question: "How many times do I circle the Ka'bah?", answer: "Seven complete circuits, counterclockwise. Each circuit starts and ends at the Black Stone." },
      { id: "q2", question: "Do I need Wudu for Tawaf?", answer: "Yes. Being in a state of Wudu is a condition of valid Tawaf. If it breaks during Tawaf, most scholars say you should renew Wudu and continue from where you left off." },
      { id: "q3", question: "What if I lose count of my circuits?", answer: "If you are unsure whether you have completed four or five circuits, assume the lesser number (four) and continue. Completing seven circuits is essential." },
      { id: "q4", question: "Can I make du'a in my own language during Tawaf?", answer: "Yes. There is no specific mandatory du'a for each circuit. You are free to supplicate to Allah in any language." },
      { id: "q5", question: "What is Idtiba'?", answer: "Idtiba' is when a male pilgrim drapes his upper Ihram sheet under his right arm, leaving the right shoulder bare. It applies during Tawaf al-Qudum only." },
      { id: "q6", question: "What is Ramal?", answer: "Ramal is brisk walking with short steps. Male pilgrims perform it during the first three circuits of Tawaf al-Qudum." },
      { id: "q7", question: "Must I touch the Black Stone?", answer: "No. If it is not possible due to crowds, point toward it while saying 'Allahu Akbar.' This is fully acceptable." },
      { id: "q8", question: "What do I do after completing seven circuits?", answer: "Proceed to Maqam Ibrahim and pray two rak'ahs if possible. Then you may drink Zamzam water before proceeding to Sa'i." },
      { id: "q9", question: "What is the Yemeni Corner?", answer: "The Yemeni Corner (ar-Rukn al-Yamani) is the corner of the Ka'bah facing Yemen. It is touched with the right hand when passing it during Tawaf." },
      { id: "q10", question: "What if my Wudu breaks during Tawaf?", answer: "Leave, renew your Wudu, return, and continue from the circuit where you left off. You do not need to start from the beginning." },
      { id: "q11", question: "Is there a specific time for Tawaf?", answer: "Tawaf can be performed at any time, day or night. There is no specific time restriction." },
      { id: "q12", question: "What is the difference between Tawaf al-Qudum and Tawaf al-Ifadah?", answer: "Tawaf al-Qudum is the arrival Tawaf performed on entering Makkah. Tawaf al-Ifadah is the obligatory Tawaf performed on the 10th of Dhul Hijjah during Hajj." },
    ]},
    { type: "narrativeText", title: "Scholar Notes", icon: "BookOpen", paragraphs: [
      "Scholars across the major schools of Islamic jurisprudence agree that Tawaf is one of the pillars of Hajj. Its conditions include being in a state of purity, circling counterclockwise, keeping the Ka'bah on the left, and completing seven circuits.",
      "Ibn Hajar al-'Asqalani and other classical scholars noted that Tawaf is a form of prayer in motion—which is why speech during it should be limited to dhikr, du'a, and recitation of Qur'an.",
    ]},
    { type: "companionTool", title: "Understanding Tawaf", description: "Explore the Ka'bah, the Black Stone, the Yemeni Corner, and Maqam Ibrahim to deepen your understanding of the sacred sites connected to Tawaf.", ctaLabel: "Open Sacred Places", ctaScreen: "SacredPlaces", ctaMode: "root" },
    { type: "narrativeText", title: "References", icon: "BookOpen", paragraphs: [
      "Qur'an — Surah Al-Hajj (22:29)",
      "Qur'an — Surah Al-Baqarah (2:125)",
      "Hadith — Sahih al-Bukhari, Book of Hajj",
      "Hadith — Sahih Muslim, Book of Hajj",
      "Classical Scholarship — Imam an-Nawawi, Al-Majmu'; Ibn Qudamah, Al-Mughni; Ibn Hajar al-'Asqalani",
      "Contemporary Guidance — Saudi Ministry of Hajj & Umrah; General Authority for the Care of the Two Holy Mosques",
    ]},
    { type: "insight", title: "My Notes Prompt", icon: "NotePencil", text: "As you imagine yourself performing Tawaf, what would you want to say to Allah with each step? Write down a personal du'a or reflection you would carry into the circuits." },
  ],
};
