import hajjLesson8Cover from "../../assets/lesson_images/hajj_lesson8.png";

export const LESSON_HAJJ_08 = {
  id: "hajj-08",
  guide: "hajj",
  lessonNumber: 8,
  totalLessons: 16,
  title: "Maqam Ibrahim & Zamzam",
  blocks: [
    { type: "cover", image: hajjLesson8Cover, lessonBadge: "LESSON 8 OF 16", title: "Maqam Ibrahim & Zamzam", subtitle: "Discover the sacred sites that follow Tawaf—and the stories of faith and trust they carry.", readingMinutes: 8 },
    { type: "cardList", title: "After This Lesson You'll Understand", cards: [
      { id: "c1", icon: "Question", label: "What Maqam Ibrahim is and why it is significant." },
      { id: "c2", icon: "Heart", label: "The story of Zamzam and why it is sacred." },
      { id: "c3", icon: "BookOpen", label: "What the two rak'ahs after Tawaf mean and where to pray them." },
      { id: "c4", icon: "Star", label: "The etiquette of drinking Zamzam water." },
    ]},
    { type: "narrativeText", title: "Overview", icon: "BookOpen", paragraphs: [
      "After completing the seven circuits of Tawaf, the pilgrim proceeds to Maqam Ibrahim to pray two rak'ahs, before drinking from the blessed Zamzam well. Both of these acts are deeply connected to the legacy of Prophet Ibrahim (AS) and his family.",
      "Maqam Ibrahim—the Station of Ibrahim—is a stone that bears the imprint of the Prophet Ibrahim's feet, preserved as a sign of the miracle Allah granted during the construction of the Ka'bah.",
    ]},
    { type: "narrativeText", title: "Maqam Ibrahim", icon: "Star", paragraphs: [
      "When Prophet Ibrahim (AS) and his son Isma'il (AS) were building the Ka'bah, the walls grew too high to reach without assistance. Allah caused the stone beneath Ibrahim's feet to rise as he stood upon it, and his footprints were miraculously preserved in it.",
      "Allah commands in the Qur'an: 'Take from the station of Ibrahim a place of prayer.' After Tawaf, the pilgrim prays two rak'ahs as close to Maqam Ibrahim as possible, following this divine instruction.",
    ]},
    { type: "narrativeText", title: "The Story of Zamzam", icon: "Heart", paragraphs: [
      "Prophet Ibrahim (AS) left his wife Hajar and their infant son Isma'il in the valley of Makkah by Allah's command, with only a small supply of water and dates. When the water ran out, Hajar ran between the hills of Safa and Marwah seven times in search of water for her child.",
      "Allah answered her effort by causing the spring of Zamzam to burst forth from the earth beneath the infant Isma'il's feet. The well has continued to flow ever since, providing water to pilgrims across centuries.",
    ]},
    { type: "narrativeText", title: "Etiquette of Drinking Zamzam", icon: "MoonStars", paragraphs: [
      "The Prophet ﷺ said: 'Zamzam water is for whatever it is drunk for.' This hadith encourages the pilgrim to make du'a before drinking Zamzam, asking Allah for whatever they need in this world and the next.",
      "It is recommended to face the Ka'bah, drink three draughts to your fill, and say 'Bismillah' before drinking and 'Alhamdulillah' after, following the description reported in Sunan Ibn Majah.",
    ]},
    { type: "narrativeText", title: "What Comes After", icon: "BookOpen", paragraphs: [
      "After praying the two rak'ahs at Maqam Ibrahim and drinking Zamzam, the pilgrim proceeds to perform Sa'i—the walk between Safa and Marwah that commemorates Hajar's search for water.",
      "The sequence from Tawaf to Maqam Ibrahim to Zamzam to Sa'i forms one continuous act of devotion, each part flowing from the legacy of the family of Ibrahim (AS).",
    ]},
    { type: "numberedSteps", title: "What to Do After Tawaf", steps: [
      { heading: "Proceed to Maqam Ibrahim", body: "After your seventh circuit ends at the Black Stone, move toward Maqam Ibrahim while reciting: 'Wattakhidhu min maqami Ibrahima musalla' (And take from the station of Ibrahim a place of prayer — Qur'an 2:125)." },
      { heading: "Pray Two Rak'ahs", body: "Pray two rak'ahs with Maqam Ibrahim between you and the Ka'bah. In the first rak'ah, recite Surah Al-Kafirun after Al-Fatihah; in the second, recite Surah Al-Ikhlas." },
      { heading: "Return to the Black Stone", body: "After the two rak'ahs, return to the Black Stone to acknowledge it once more before proceeding to Zamzam." },
      { heading: "Drink Zamzam", body: "Go to the Zamzam drinking stations. Face the Ka'bah, say 'Bismillah,' make du'a, and drink three draughts to your fill." },
      { heading: "Proceed to Sa'i", body: "After Zamzam, walk toward Safa to begin Sa'i. You may walk or use the wheelchair ramps. Sa'i begins from Safa." },
    ]},
    { type: "cardList", title: "Things to Remember", cards: [
      { id: "t1", icon: "Star", label: "Two rak'ahs are prayed at Maqam Ibrahim after Tawaf." },
      { id: "t2", icon: "Heart", label: "Maqam Ibrahim is the stone bearing Prophet Ibrahim's footprints." },
      { id: "t3", icon: "MoonStars", label: "Zamzam water is blessed and flows miraculously since Hajar's time." },
      { id: "t4", icon: "Question", label: "Make du'a before drinking Zamzam for what you need most." },
      { id: "t5", icon: "BookOpen", label: "Face the Ka'bah when drinking Zamzam." },
      { id: "t6", icon: "ListChecks", label: "Sa'i follows after Zamzam to complete this sequence." },
    ]},
    { type: "cardList", title: "Key Takeaways", cards: [
      { id: "k1", icon: "Star", label: "Maqam Ibrahim marks Allah's miracle during the construction of the Ka'bah." },
      { id: "k2", icon: "Heart", label: "Zamzam is a gift born from Hajar's trust in Allah." },
      { id: "k3", icon: "BookOpen", label: "The two rak'ahs fulfill the Qur'anic command to take Maqam Ibrahim as a place of prayer." },
      { id: "k4", icon: "Question", label: "Zamzam water is for whatever it is drunk for." },
      { id: "k5", icon: "MoonStars", label: "Each act connects the pilgrim to the legacy of the family of Ibrahim (AS)." },
    ]},
    { type: "insight", title: "A Moment to Notice", text: "The footprints of Prophet Ibrahim (AS) in the stone of Maqam Ibrahim are a reminder that what Allah wills to be remembered, is remembered. Thousands of years have passed, and still the mark of his feet remains." },
    { type: "insight", title: "Insight", text: "Hajar did not know where the water would come from. She ran, not because she could see the answer, but because she trusted that Allah would provide. The spring of Zamzam is the enduring answer to that trust. Every sip you take carries that story." },
    { type: "insight", title: "Reflection", text: "What du'a would you make before drinking from Zamzam? What do you need from Allah—for this life, and for the next?" },
    { type: "cardList", title: "Practice", cards: [
      { id: "p1", icon: "Star", label: "Memorise the Qur'anic verse about Maqam Ibrahim: 'Wattakhidhu min maqami Ibrahima musalla' (2:125)." },
      { id: "p2", icon: "Heart", label: "Read the story of Hajar, Isma'il, and the spring of Zamzam." },
      { id: "p3", icon: "BookOpen", label: "Learn which surahs to recite in the two rak'ahs after Tawaf." },
      { id: "p4", icon: "MoonStars", label: "Prepare a personal du'a you would want to make when drinking Zamzam." },
      { id: "p5", icon: "Question", label: "Reflect on what trust in Allah looked like for Hajar and what it looks like for you." },
      { id: "p6", icon: "ListChecks", label: "Understand the sequence: Tawaf → Maqam Ibrahim → Zamzam → Sa'i." },
    ]},
    { type: "qaCardList", title: "Common Questions", cards: [
      { id: "q1", question: "Where do I pray after Tawaf?", answer: "At Maqam Ibrahim, the stone bearing the footprints of Prophet Ibrahim (AS), with Maqam Ibrahim between you and the Ka'bah." },
      { id: "q2", question: "What do I recite in the two rak'ahs?", answer: "In the first rak'ah, recite Surah Al-Kafirun after Al-Fatihah. In the second, recite Surah Al-Ikhlas after Al-Fatihah." },
      { id: "q3", question: "What is Maqam Ibrahim?", answer: "It is the stone on which Prophet Ibrahim (AS) stood while building the Ka'bah. His footprints were miraculously preserved in it by Allah." },
      { id: "q4", question: "Is it obligatory to pray exactly at Maqam Ibrahim?", answer: "It is Sunnah to pray as close to Maqam Ibrahim as possible. If it is very crowded, you may pray anywhere in the mosque." },
      { id: "q5", question: "What du'a should I make when drinking Zamzam?", answer: "There is no specific prescribed du'a. The Prophet ﷺ said Zamzam is for whatever it is drunk for, so supplicate for what you need most in this life and the next." },
      { id: "q6", question: "Is Zamzam water really miraculous?", answer: "Yes. It has flowed without interruption for thousands of years and is confirmed by scientific studies to have unique mineral composition and purity." },
      { id: "q7", question: "How do I drink Zamzam correctly?", answer: "Face the Ka'bah, say 'Bismillah,' make du'a, drink three draughts to your fill, and say 'Alhamdulillah' afterward." },
      { id: "q8", question: "Can I take Zamzam water home?", answer: "Yes. Many pilgrims carry Zamzam water as a gift for family and friends at home." },
      { id: "q9", question: "What happens if I cannot pray at Maqam Ibrahim due to crowds?", answer: "You may pray the two rak'ahs anywhere in Masjid al-Haram. The condition is that you pray them after Tawaf." },
      { id: "q10", question: "What does the Qur'an say about Maqam Ibrahim?", answer: "Surah Al-Baqarah (2:125): 'And We charged Ibrahim and Isma'il: Purify My House for those who circle it, those who stay there for devotion, and those who bow and prostrate. And take from the station of Ibrahim a place of prayer.'" },
      { id: "q11", question: "Does Zamzam water expire?", answer: "Zamzam water stays pure for a very long time when stored properly. Scholars and scientists have noted its exceptional purity and stability." },
      { id: "q12", question: "What comes after Zamzam?", answer: "Sa'i—the walk between Safa and Marwah—which commemorates Hajar's search for water for her child." },
    ]},
    { type: "narrativeText", title: "Scholar Notes", icon: "BookOpen", paragraphs: [
      "Scholars have agreed that praying two rak'ahs at Maqam Ibrahim after Tawaf is strongly recommended (Sunnah mu'akkadah). The Qur'anic command to take Maqam Ibrahim as a place of prayer was acted upon by the Prophet ﷺ during his Farewell Pilgrimage.",
      "Ibn al-Qayyim and others wrote extensively on the blessing of Zamzam water, noting that it is among the greatest gifts Allah has placed in the earth—a response to sincere need and an answer to a mother's trust in her Lord.",
    ]},
    { type: "companionTool", title: "Sacred Stories", description: "Explore the story of Maqam Ibrahim, the spring of Zamzam, and their place within the sacred geography of Masjid al-Haram.", ctaLabel: "Open Sacred Places", ctaScreen: "SacredPlaces", ctaMode: "root" },
    { type: "narrativeText", title: "References", icon: "BookOpen", paragraphs: [
      "Qur'an — Surah Al-Baqarah (2:125–127)",
      "Qur'an — Surah Ibrahim (14:37)",
      "Hadith — Sahih al-Bukhari, Book of Hajj",
      "Hadith — Sahih Muslim, Book of Hajj",
      "Hadith — Ibn Majah: 'Zamzam water is for whatever it is drunk for.'",
      "Classical Scholarship — Imam an-Nawawi; Ibn al-Qayyim; Ibn Hajar al-'Asqalani",
      "Contemporary Guidance — Saudi Ministry of Hajj & Umrah; General Authority for the Care of the Two Holy Mosques",
    ]},
    { type: "insight", title: "My Notes Prompt", icon: "NotePencil", text: "Which story speaks to you more today — the miracle of Ibrahim's footprints or the spring that answered Hajar's trust? What does it tell you about how Allah responds to those who believe?" },
  ],
};
