import hajjLesson2Cover from "../../assets/lesson_images/hajj_lesson2.png";

export const LESSON_HAJJ_02 = {
  id: "hajj-02",
  guide: "hajj",
  lessonNumber: 2,
  totalLessons: 16,
  title: "Understanding Hajj",
  blocks: [
    { type: "cover", image: hajjLesson2Cover, lessonBadge: "LESSON 2 OF 16", title: "Understanding Hajj", subtitle: "Discover the purpose, significance, and meaning of Hajj as one of the Five Pillars of Islam.", readingMinutes: 7 },
    { type: "cardList", title: "After This Lesson You'll Understand", cards: [
      { id: "c1", icon: "Question", label: "What Hajj is and why it is one of the Five Pillars." },
      { id: "c2", icon: "MoonStars", label: "Who Hajj is required for." },
      { id: "c3", icon: "BookOpen", label: "What makes Hajj different from Umrah." },
      { id: "c4", icon: "Star", label: "Why the pilgrimage unfolds through sacred time and place." },
      { id: "c5", icon: "Heart", label: "The deeper purpose of the journey." },
    ]},
    { type: "narrativeText", title: "Overview", icon: "BookOpen", paragraphs: [
      "Hajj is the annual pilgrimage to Makkah and one of the Five Pillars of Islam. It is an obligation upon every Muslim who is physically, financially, and safely able to perform it at least once during their lifetime.",
      "Unlike Umrah, Hajj is performed only during specific days in the month of Dhul Hijjah and follows a sequence of sacred rites established through the traditions of Prophet Ibrahim (AS) and demonstrated by Prophet Muhammad ﷺ. For millions of Muslims, Hajj is the culmination of a lifetime of hope, preparation, and worship.",
    ]},
    { type: "narrativeText", title: "Why it Matters", icon: "Heart", paragraphs: [
      "Hajj is more than a journey to a sacred place. It is a journey of worship, humility, sacrifice, remembrance, and unity.",
      "Pilgrims leave behind the comforts and distinctions of daily life to stand alongside Muslims from every nation, language, and background. The pilgrimage reminds us that before Allah, true honor is found through faith and righteousness—not wealth, status, or appearance.",
    ]},
    { type: "narrativeText", title: "Historical Context", icon: "BookOpen", paragraphs: [
      "The origins of Hajj begin with Prophet Ibrahim (AS), who, together with his son Isma'il (AS), rebuilt the Ka'bah as a place dedicated to the worship of Allah. Allah then commanded Ibrahim (AS), \"And proclaim the pilgrimage to mankind...\"",
      "For generations, pilgrims answered this call. Centuries later, Prophet Muhammad ﷺ restored Hajj to its original purpose and taught Muslims how to perform its rites with sincerity and devotion. Today, every pilgrim continues that same sacred tradition.",
    ]},
    { type: "narrativeText", title: "What Makes Hajj Unique", icon: "Star", paragraphs: [
      "Hajj is one of the foundational acts of worship in Islam and, for those who are able, a once-in-a-lifetime obligation. It can only be performed during the designated days of Dhul Hijjah.",
      "These days form one connected journey, with each stage building upon the last. Hajj unfolds over several sacred days and culminates in the Standing at Arafah—often described as the heart of Hajj. It is also a universal gathering in which pilgrims from different nations, languages, and backgrounds follow the same rites together.",
    ]},
    { type: "narrativeText", title: "Hajj & Umrah", icon: "ListChecks", paragraphs: [
      "Although they share some rituals, Hajj and Umrah are distinct acts of worship. Hajj is one of the Five Pillars, is performed during specific days, includes Mina, Arafah, Muzdalifah, and Jamarat, and takes several days.",
      "Umrah can be performed throughout most of the year, does not include these Hajj locations and rites, and is usually completed within a few hours.",
    ]},
    { type: "numberedSteps", title: "Step-by-Step", steps: [
      { heading: "Begin with the Big Picture", body: "See Hajj as one connected journey. The stages are not isolated actions. Each location, day, and rite builds toward the larger pilgrimage." },
      { heading: "Understand Sacred Time", body: "Recognize why the timing matters. Unlike Umrah, Hajj is tied to specific days in Dhul Hijjah. The sacred time is part of the structure of the pilgrimage." },
      { heading: "Understand Sacred Places", body: "Learn the main locations. Begin becoming familiar with Makkah, Mina, Arafah, Muzdalifah, and the Jamarat so the journey has a mental map." },
      { heading: "Recognize the Legacy", body: "See yourself within a much older tradition. Hajj connects today's pilgrims with the legacy of Prophet Ibrahim (AS), his family, and the example of Prophet Muhammad ﷺ." },
      { heading: "Reflect on Unity", body: "Notice what changes when distinctions fall away. Pilgrims from every background gather to worship Allah together, reinforcing humility, equality, and the unity of the Muslim community." },
    ]},
    { type: "cardList", title: "Things to Remember", cards: [
      { id: "t1", icon: "Star", label: "Hajj is obligatory for those who are able." },
      { id: "t2", icon: "BookOpen", label: "It takes place during the days of Dhul Hijjah." },
      { id: "t3", icon: "ListChecks", label: "It follows a specific sequence of stages." },
      { id: "t4", icon: "Question", label: "Every rite has a historical and spiritual significance." },
      { id: "t5", icon: "Heart", label: "The journey combines worship, sacrifice, and remembrance." },
      { id: "t6", icon: "MoonStars", label: "Hajj commemorates the legacy of Prophet Ibrahim (AS) and his family." },
      { id: "t7", icon: "Star", label: "It is distinct from Umrah even though some rites are shared." },
      { id: "t8", icon: "BookOpen", label: "The Standing at Arafah is a central part of the Hajj journey." },
      { id: "t9", icon: "Heart", label: "The pilgrimage brings Muslims from different backgrounds together in worship." },
    ]},
    { type: "cardList", title: "Key Takeaways", cards: [
      { id: "k1", icon: "Star", label: "Hajj is one of Islam's Five Pillars." },
      { id: "k2", icon: "Heart", label: "It commemorates the legacy of Prophet Ibrahim (AS) and his family." },
      { id: "k3", icon: "MoonStars", label: "It can only be performed during specific days." },
      { id: "k4", icon: "BookOpen", label: "It unfolds as one connected journey through sacred time and place." },
      { id: "k5", icon: "ListChecks", label: "It is distinct from Umrah, even though some rites are shared." },
      { id: "k6", icon: "Question", label: "Its deeper purpose includes worship, humility, sacrifice, remembrance, and unity." },
    ]},
    { type: "insight", title: "Insight", text: "Many people describe Hajj as the journey of a lifetime. In reality, it is the journey of many lifetimes. Every generation since Prophet Ibrahim (AS) has answered the same call, walked the same valleys, stood on the same plain of Arafah, and worshipped the same Lord. When you perform Hajj, you become part of a tradition that stretches back thousands of years." },
    { type: "cardList", title: "Practice", cards: [
      { id: "p1", icon: "BookOpen", label: "Read the translation of Qur'an 22:27–29." },
      { id: "p2", icon: "Star", label: "Learn the names of the main locations of Hajj." },
      { id: "p3", icon: "ListChecks", label: "Familiarize yourself with the overall journey from Makkah to Mina, Arafah, Muzdalifah, and back again." },
      { id: "p4", icon: "Question", label: "Compare Hajj and Umrah using the four distinctions: obligation, timing, rites and locations, and duration." },
      { id: "p5", icon: "Heart", label: "Write one sentence describing what you believe the deeper purpose of Hajj is." },
    ]},
    { type: "qaCardList", title: "Common Questions", cards: [
      { id: "q1", question: "Is Hajj required more than once?", answer: "No. For those who are able, Hajj is obligatory once in a lifetime. Additional pilgrimages are voluntary." },
      { id: "q2", question: "Can Umrah replace Hajj?", answer: "No. Umrah is a distinct act of worship and does not fulfill the obligation of Hajj." },
      { id: "q3", question: "Why is Hajj only performed during certain days?", answer: "Allah prescribed specific days for Hajj, and the pilgrimage follows the sequence taught by the Prophet ﷺ. These days are an essential part of the rite itself." },
      { id: "q4", question: "What makes Hajj different from Umrah?", answer: "Hajj is one of the Five Pillars, occurs during specific days, includes Mina, Arafah, Muzdalifah, and Jamarat, and takes several days. Umrah can be performed throughout most of the year, does not include these Hajj rites, and is usually completed within a few hours." },
      { id: "q5", question: "Why is Arafah so important?", answer: "The Standing at Arafah is described as the culmination of the sacred days and often as the heart of Hajj." },
      { id: "q6", question: "Why is Hajj connected to Prophet Ibrahim (AS)?", answer: "The origins of Hajj trace to Prophet Ibrahim (AS) and his son Isma'il (AS), who rebuilt the Ka'bah as a place dedicated to Allah." },
      { id: "q7", question: "Why do Muslims from so many countries gather for Hajj?", answer: "The pilgrimage brings Muslims from every nation, language, and background together to worship Allah through the same rites." },
      { id: "q8", question: "Is Hajj mainly a physical journey?", answer: "No. It is a journey of worship, humility, sacrifice, remembrance, and unity." },
      { id: "q9", question: "Does Hajj have to be understood before I begin the rituals?", answer: "Understanding the purpose and sequence beforehand helps pilgrims worship with greater presence and confidence." },
      { id: "q10", question: "Why does Hajj take several days?", answer: "Hajj is a connected journey through sacred time, with each stage building upon the last." },
      { id: "q11", question: "What should I learn first?", answer: "Begin with the big picture: the main locations, the sacred days, and the overall sequence. This will make the individual stages easier to understand." },
      { id: "q12", question: "What does Hajj teach about equality?", answer: "Pilgrims leave behind many ordinary distinctions and stand together in worship, reminding them that true honor before Allah is found through faith and righteousness." },
    ]},
    { type: "narrativeText", title: "Scholar Notes", icon: "BookOpen", paragraphs: [
      "Understanding the purpose and sequence of Hajj before beginning its rituals helps pilgrims worship with greater presence and confidence. Learning why each stage exists makes it easier to appreciate the wisdom behind the pilgrimage and avoid viewing it as a series of disconnected actions.",
      "Hajj is also part of a tradition stretching back through generations to Prophet Ibrahim (AS).",
    ]},
    { type: "narrativeText", title: "References", icon: "BookOpen", paragraphs: [
      "Qur'an — Surah Aal 'Imran (3:97)",
      "Qur'an — Surah Al-Hajj (22:27–37)",
      "Qur'an — Surah Al-Baqarah (2:196–203)",
      "Hadith — Sahih al-Bukhari, Book of Hajj",
      "Hadith — Sahih Muslim, Book of Hajj",
      "Classical Scholarship — Imam an-Nawawi; Ibn Qudamah; Ibn Hajar al-'Asqalani",
      "Contemporary Guidance — Saudi Ministry of Hajj & Umrah; General Authority for the Care of the Two Holy Mosques",
    ]},
  ],
};
