import hajjLesson1Cover from "../../assets/lesson_images/hajj_lesson1.png";

export const LESSON_HAJJ_01 = {
  id: "hajj-01",
  guide: "hajj",
  lessonNumber: 1,
  totalLessons: 16,
  title: "Preparing for Hajj",
  blocks: [
    { type: "cover", image: hajjLesson1Cover, lessonBadge: "LESSON 1 OF 16", title: "Preparing for Hajj", subtitle: "Prepare your heart, mind, and practical affairs for the greatest journey of your life.", readingMinutes: 6 },
    { type: "cardList", title: "After This Lesson You'll Understand", cards: [
      { id: "c1", icon: "Question", label: "Why preparation begins long before you arrive in Makkah." },
      { id: "c2", icon: "MoonStars", label: "The spiritual and practical preparations for Hajj." },
      { id: "c3", icon: "BookOpen", label: "What Hajj requires of every pilgrim." },
      { id: "c4", icon: "Star", label: "How to begin your journey with sincerity and confidence." },
    ]},
    { type: "narrativeText", title: "Overview", icon: "BookOpen", paragraphs: [
      "Hajj is one of the Five Pillars of Islam and one of the greatest acts of worship a Muslim can perform. For those who are physically and financially able, it is an obligation to perform Hajj once in a lifetime.",
      "Preparing for Hajj is about far more than packing a suitcase. It begins by preparing your heart, renewing your intention, learning the pilgrimage, and making the necessary practical arrangements before you travel. The more prepared you are before leaving home, the more present you can be during the pilgrimage itself.",
    ]},
    { type: "narrativeText", title: "Why it Matters", icon: "Heart", paragraphs: [
      "Hajj is unlike any other journey. For several sacred days, millions of Muslims from every nation gather to worship Allah together, following the footsteps of Prophet Ibrahim (AS), Hajar (AS), and Prophet Muhammad ﷺ.",
      "Preparation allows you to approach this journey with knowledge rather than uncertainty, giving you the confidence to focus on worship instead of logistics.",
    ]},
    { type: "narrativeText", title: "Historical Context", icon: "BookOpen", paragraphs: [
      "Hajj traces its origins to Prophet Ibrahim (AS), who, by Allah's command, established the Ka'bah as a place of worship.",
      "Generations later, Prophet Muhammad ﷺ restored the pilgrimage to the pure worship of Allah and demonstrated how its rites should be performed. Today, Muslims continue this tradition by following the same sacred journey.",
    ]},
    { type: "numberedSteps", title: "How to Prepare", steps: [
      { heading: "Strengthen Your Intention", body: "Renew your intention solely for Allah. Hajj is an act of worship—not a holiday, cultural experience, or personal achievement." },
      { heading: "Learn Before You Travel", body: "Understand the stages of Hajj before you arrive. Learning the pilgrimage helps you perform each rite with confidence and purpose." },
      { heading: "Seek Forgiveness", body: "Begin with a clean heart. Ask Allah for forgiveness, reconcile with others where possible, and seek to begin your pilgrimage with a clean heart." },
      { heading: "Organize Your Affairs", body: "Handle important responsibilities before leaving. Arrange travel documents, prepare medications, settle debts if possible, write a will if appropriate, and inform family of your plans." },
      { heading: "Prepare Physically", body: "Give yourself time to prepare for the demands of the journey. Hajj requires walking, patience, and endurance. Think ahead about rest, hydration, appropriate footwear, medications, and managing your energy." },
      { heading: "Prepare Your Family", body: "Reduce unfinished responsibilities at home. Make sure family members know your plans and have the information they may need while you are away." },
      { heading: "Pack Thoughtfully", body: "Bring what you need, but travel lightly. Simple, practical preparation allows you to focus on worship rather than possessions." },
    ]},
    { type: "cardList", title: "Things to Remember", cards: [
      { id: "t1", icon: "Star", label: "Hajj is obligatory once in a lifetime for those who are able." },
      { id: "t2", icon: "BookOpen", label: "Preparation begins long before entering Ihram." },
      { id: "t3", icon: "ListChecks", label: "Learn the pilgrimage before you travel." },
      { id: "t4", icon: "Heart", label: "Renew your intention often." },
      { id: "t5", icon: "Question", label: "Take care of practical responsibilities early." },
      { id: "t6", icon: "MoonStars", label: "Prepare physically for walking, crowds, and long days." },
      { id: "t7", icon: "Star", label: "Keep your packing simple and purposeful." },
      { id: "t8", icon: "Heart", label: "Be patient when plans or conditions change." },
      { id: "t9", icon: "BookOpen", label: "Trust Allah throughout your journey." },
    ]},
    { type: "cardList", title: "Key Takeaways", cards: [
      { id: "k1", icon: "Star", label: "Hajj is one of Islam's Five Pillars." },
      { id: "k2", icon: "Heart", label: "Good preparation brings peace of mind." },
      { id: "k3", icon: "MoonStars", label: "Spiritual preparation is just as important as practical preparation." },
      { id: "k4", icon: "BookOpen", label: "Learning before you travel helps you worship with confidence." },
      { id: "k5", icon: "ListChecks", label: "Taking care of worldly responsibilities creates space for worship." },
      { id: "k6", icon: "Question", label: "The journey begins with a sincere response to Allah's call." },
    ]},
    { type: "insight", title: "Insight", text: "The first step of Hajj is not entering Ihram. It is making the sincere decision to answer Allah's call. Every checklist completed, every lesson learned, and every du'a made before departure becomes part of your pilgrimage. Preparation itself is an act of worship when done with the right intention." },
    { type: "cardList", title: "Practice", cards: [
      { id: "p1", icon: "BookOpen", label: "Learn the overall stages of Hajj." },
      { id: "p2", icon: "Heart", label: "Begin your personal du'a list." },
      { id: "p3", icon: "ListChecks", label: "Create your packing checklist." },
      { id: "p4", icon: "Question", label: "Review your travel documents." },
      { id: "p5", icon: "MoonStars", label: "Discuss your journey with family." },
      { id: "p6", icon: "Star", label: "Identify practical responsibilities that need to be completed before departure." },
    ]},
    { type: "qaCardList", title: "Common Questions", cards: [
      { id: "q1", question: "Who is required to perform Hajj?", answer: "Hajj is obligatory once in a lifetime for every Muslim who is physically, financially, and safely able to undertake the journey." },
      { id: "q2", question: "Is Hajj obligatory only once in a lifetime?", answer: "For a person who meets the conditions of ability, the obligatory Hajj is once in a lifetime. Additional Hajj may be performed voluntarily." },
      { id: "q3", question: "What does being physically and financially able mean?", answer: "Ability is generally framed as being physically and financially able to undertake the journey. Specific circumstances can differ, so detailed questions should be taken to a trusted scholar." },
      { id: "q4", question: "Does safety matter when determining whether Hajj is obligatory?", answer: "Yes. Being safely able to undertake the journey is included among the conditions for the obligation." },
      { id: "q5", question: "When should I start preparing for Hajj?", answer: "Begin as early as practical. Preparation starts long before entering Ihram and includes learning, spiritual preparation, and organizing your affairs." },
      { id: "q6", question: "Is preparation itself one of the ritual acts of Hajj?", answer: "No. Preparation is not itself a ritual act of Hajj, but it can greatly influence your ability to perform the pilgrimage with understanding, focus, and peace of mind." },
      { id: "q7", question: "Should I memorize every du'a before I go?", answer: "No. Focus first on understanding the meaning and purpose of each stage. You can continue learning du'as throughout your preparation." },
      { id: "q8", question: "What should I learn before travelling?", answer: "Start with the overall stages of Hajj and learn what happens at each stage. Understanding the journey beforehand helps you worship with confidence." },
      { id: "q9", question: "What practical affairs should I take care of before Hajj?", answer: "Arranging travel documents, preparing medications, settling debts if possible, writing a will if appropriate, informing family of your plans, and packing thoughtfully." },
      { id: "q10", question: "Should I settle my debts before leaving?", answer: "Settling debts if possible is specifically included among the practical affairs to address before departure." },
      { id: "q11", question: "Should I make a will before Hajj?", answer: "Writing a will if appropriate is recommended as part of organizing your affairs before leaving." },
      { id: "q12", question: "How can I prepare spiritually?", answer: "Renew your intention solely for Allah, seek forgiveness, reconcile with others where possible, begin a personal du'a list, and learn the pilgrimage before you travel." },
    ]},
    { type: "narrativeText", title: "Scholar Notes", icon: "BookOpen", paragraphs: [
      { heading: "Knowledge before action" },
      "Islamic scholarship has emphasized learning the rites of Hajj before performing them so that worship is approached with understanding rather than imitation. Seeking knowledge before action helps the pilgrim approach each stage with confidence and sincerity.",
      { heading: "Ability and obligation" },
      "Hajj is obligatory for the Muslim who is physically, financially, and safely able to undertake it. Because individual circumstances can differ, questions about a person's specific ability or obligation should be taken to a trusted scholar.",
      { heading: "Preparation and ritual are distinct" },
      "Preparing for Hajj is not itself one of the ritual acts of Hajj. Its value is that it helps the pilgrim reach the pilgrimage ready to worship with understanding, focus, and peace of mind.",
    ]},
    { type: "narrativeText", title: "References", icon: "BookOpen", paragraphs: [
      "Qur'an — Surah Aal 'Imran (3:97)",
      "Qur'an — Surah Al-Hajj (22:27–29)",
      "Qur'an — Surah Al-Baqarah (2:196–203)",
      "Hadith — Sahih al-Bukhari, Book of Hajj",
      "Hadith — Sahih Muslim, Book of Hajj",
      "Classical Scholarship — Imam an-Nawawi; Ibn Qudamah; Ibn Hajar al-'Asqalani",
      "Contemporary Guidance — Saudi Ministry of Hajj & Umrah; General Authority for the Care of the Two Holy Mosques",
    ]},
  ],
};
