import hajjLesson16Cover from "../../assets/lesson_images/hajj_lesson16.png";

export const LESSON_HAJJ_16 = {
  id: "hajj-16",
  guide: "hajj",
  lessonNumber: 16,
  totalLessons: 16,
  title: "Returning Home",
  blocks: [
    { type: "cover", image: hajjLesson16Cover, lessonBadge: "LESSON 16 OF 16", title: "Returning Home", subtitle: "The pilgrimage may be complete, but its greatest lessons are only beginning.", readingMinutes: 9 },
    { type: "cardList", title: "After This Lesson You'll Understand", cards: [
      { id: "c1", icon: "Question", label: "Why Hajj is the beginning of a lifelong journey." },
      { id: "c2", icon: "Heart", label: "How to carry its lessons into everyday life." },
      { id: "c3", icon: "Star", label: "Practical ways to preserve spiritual momentum after Hajj." },
      { id: "c4", icon: "MoonStars", label: "How to continue growing after returning home." },
      { id: "c5", icon: "BookOpen", label: "How small, consistent habits can keep the pilgrimage alive in ordinary life." },
    ]},
    { type: "narrativeText", title: "Overview", icon: "BookOpen", paragraphs: [
      "Eventually, every pilgrim boards a plane, packs away their Ihram, and returns home. Daily routines begin again. Work resumes. School starts. Laundry waits. Emails pile up. Life continues.",
      "Yet something has changed. Hajj was never meant to be an escape from ordinary life; it was meant to prepare you to return to it with a renewed heart.",
    ]},
    { type: "narrativeText", title: "Why It Matters", icon: "Heart", paragraphs: [
      "The success of Hajj is not measured only by how many rituals were completed. The deeper question is: 'How will Hajj continue to live within me?' The goal is not to recreate every emotion of Makkah, but to preserve the habits, sincerity, and character that the pilgrimage cultivated.",
    ]},
    { type: "narrativeText", title: "The Journey Continues", icon: "Star", paragraphs: [
      "During Hajj, the day revolved around prayer. After returning home, let prayer remain an anchor. Do not leave your conversations with Allah in Makkah. Continue with Qur'an, remembrance, charity, patience, compassion, and service to others.",
    ]},
    { type: "narrativeText", title: "Consistency Over Intensity", icon: "MoonStars", paragraphs: [
      "A few minutes of Qur'an each day, regular du'a, morning and evening adhkar, voluntary fasting, charity, or simply being more patient can matter more than trying to reproduce an extraordinary pilgrimage experience every day.",
    ]},
    { type: "narrativeText", title: "Carry Hajj Into Relationships", icon: "Heart", paragraphs: [
      "Hajj teaches humility, patience, generosity, and compassion. Let those qualities show up in the family, workplace, friendships, and community. Someone may never know you performed Hajj; they may simply notice that you became kinder, more patient, more grateful, or more humble.",
    ]},
    { type: "narrativeText", title: "The After Hajj Plan", icon: "BookOpen", paragraphs: [
      "Choose three habits you want to continue. Options include praying on time, daily Qur'an, morning and evening adhkar, regular charity, voluntary fasting, attending the masjid, being more patient, and calling parents more often.",
    ]},
    { type: "cardList", title: "Things to Remember", cards: [
      { id: "t1", icon: "Star", label: "Hajj ends, but worship continues." },
      { id: "t2", icon: "Heart", label: "Protect the habits built during the pilgrimage." },
      { id: "t3", icon: "MoonStars", label: "Continue seeking Allah with sincerity." },
      { id: "t4", icon: "Question", label: "Let Hajj shape your character." },
      { id: "t5", icon: "BookOpen", label: "Small, consistent acts are valuable." },
      { id: "t6", icon: "ListChecks", label: "Stay connected to Qur'an and du'a." },
      { id: "t7", icon: "Star", label: "Serve others with humility and compassion." },
      { id: "t8", icon: "Heart", label: "Return often in your heart to the lessons of Hajj." },
    ]},
    { type: "cardList", title: "Key Takeaways", cards: [
      { id: "k1", icon: "Star", label: "Hajj is the beginning of lifelong spiritual growth." },
      { id: "k2", icon: "MoonStars", label: "Small, consistent acts of worship matter." },
      { id: "k3", icon: "Heart", label: "The greatest sign of meaningful Hajj is positive change in daily life." },
      { id: "k4", icon: "BookOpen", label: "Every day is another opportunity to answer Allah's call." },
      { id: "k5", icon: "Question", label: "The measure of transformation may be visible in how you treat other people." },
      { id: "k6", icon: "ListChecks", label: "Returning home is not a return to who you were; it is an opportunity to live differently." },
    ]},
    { type: "insight", title: "Insight", text: "One day, someone may never know you performed Hajj. They won't see your photos. They won't hear your stories. But they may notice something else: more patience, more kindness, more gratitude, more humility. Perhaps that is one of the most beautiful signs that Hajj fulfilled its purpose." },
    { type: "insight", title: "Reflection", text: "Imagine it is six months after your pilgrimage. You are back at work, running errands, helping your family, living an ordinary Tuesday. What do you hope is different about the way you respond to people, to difficulties, to blessings, and to Allah?" },
    { type: "cardList", title: "Practice", cards: [
      { id: "p1", icon: "BookOpen", label: "Create a simple After Hajj Plan." },
      { id: "p2", icon: "Star", label: "Choose three habits you want to continue." },
      { id: "p3", icon: "Heart", label: "Pray on time." },
      { id: "p4", icon: "MoonStars", label: "Read Qur'an daily." },
      { id: "p5", icon: "Question", label: "Make morning and evening adhkar." },
      { id: "p6", icon: "ListChecks", label: "Give charity regularly." },
      { id: "p7", icon: "Star", label: "Fast voluntary days if appropriate." },
      { id: "p8", icon: "Heart", label: "Attend the masjid more often, and practice patience." },
      { id: "p9", icon: "BookOpen", label: "Call your parents more often." },
      { id: "p10", icon: "MoonStars", label: "Review your plan after 30 days, then again after six months." },
    ]},
    { type: "insight", title: "A Moment to Notice", text: "After people ask 'How was Hajj?', perhaps the better question is 'How has Hajj changed you?' The answer may not come immediately. It may unfold quietly over months or even years." },
    { type: "qaCardList", title: "Common Questions", cards: [
      { id: "q1", question: "How do I maintain the feeling of Hajj?", answer: "Do not chase a particular feeling. Focus instead on preserving the habits and sincerity developed during Hajj." },
      { id: "q2", question: "What if my motivation fades?", answer: "This is natural. Return to the Qur'an, continue making du'a, reconnect with the lessons you learned, and remember that growth happens gradually." },
      { id: "q3", question: "Is Hajj the end of my spiritual journey?", answer: "No. For many believers, it becomes the beginning of a deeper relationship with Allah." },
      { id: "q4", question: "What habits should I continue?", answer: "Prayer, Qur'an, adhkar, charity, voluntary fasting, attending the masjid, patience, and maintaining family relationships." },
      { id: "q5", question: "Do I need to recreate the intensity of Hajj?", answer: "No. Consistency matters more than intensity." },
      { id: "q6", question: "How will I know whether Hajj changed me?", answer: "Look for changes in character, worship, relationships, patience, gratitude, humility, and consistency." },
      { id: "q7", question: "What if I struggle after returning home?", answer: "Return to the practices that grounded you during Hajj and take gradual steps rather than expecting perfection." },
      { id: "q8", question: "Why is ordinary life important?", answer: "Hajj was not meant to be an escape from ordinary life. It was meant to prepare the pilgrim to return to it with a renewed heart." },
      { id: "q9", question: "Should I keep a reflection journal?", answer: "Many pilgrims find it valuable to keep a gratitude journal or reflection journal after Hajj." },
      { id: "q10", question: "What is an After Hajj Plan?", answer: "A simple personal plan choosing a few habits to carry forward after returning home." },
      { id: "q11", question: "When should I review my goals?", answer: "Consider revisiting your plan after 30 days, then again after six months." },
      { id: "q12", question: "What is the final message of this guide?", answer: "Hajj should not simply end; its lessons are meant to become a daily companion that continues walking beside the pilgrim." },
    ]},
    { type: "narrativeText", title: "Scholar Notes", icon: "BookOpen", paragraphs: [
      "Throughout Islamic history, scholars have encouraged pilgrims to view Hajj as a turning point rather than a conclusion. A sincere pilgrimage is expected to leave a lasting effect on worship, character, and relationships. The goal is not perfection after Hajj, but continued striving toward Allah with humility and consistency.",
    ]},
    { type: "narrativeText", title: "References", icon: "BookOpen", paragraphs: [
      "Qur'an — Surah Al-Baqarah (2:197)",
      "Qur'an — Surah Al-Hajj (22:27–37)",
      "Qur'an — Surah Fussilat (41:30)",
      "Hadith — Sahih al-Bukhari, Book of Hajj",
      "Hadith — Sahih Muslim, Book of Hajj",
      "Hadith — 'The most beloved deeds to Allah are those that are consistent, even if they are small.'",
      "Classical Scholarship — Imam an-Nawawi; Ibn Qudamah; Ibn Hajar al-'Asqalani",
      "Contemporary Guidance — Saudi Ministry of Hajj & Umrah; General Authority for the Care of the Two Holy Mosques",
    ]},
    { type: "insight", title: "My Notes Prompt", icon: "NotePencil", text: "Six months from today… who do you hope you've become because of Hajj? Write a letter to your future self—not about where you traveled, but about who you hope Allah helps you become." },
    { type: "closing", image: hajjLesson16Cover, quote: "Hajj does not end in Makkah. It continues in every prayer, every kindness, and every day you choose to draw nearer to Allah.", references: [
      "Qur'an — Surah Al-Baqarah (2:197)",
      "Hadith — Sahih al-Bukhari, Book of Hajj",
      "Hadith — 'The most beloved deeds to Allah are those that are consistent, even if they are small.'",
    ]},
  ],
};
