import hajjLesson5Cover from "../../assets/lesson_images/hajj_lesson5.png";

export const LESSON_HAJJ_05 = {
  id: "hajj-05",
  guide: "hajj",
  lessonNumber: 5,
  totalLessons: 16,
  title: "Arriving in Makkah",
  blocks: [
    { type: "cover", image: hajjLesson5Cover, lessonBadge: "LESSON 5 OF 16", title: "Arriving in Makkah", subtitle: "Discover the significance of entering the sacred city where generations of believers have answered Allah's call.", readingMinutes: 6 },
    { type: "cardList", title: "After This Lesson You'll Understand", cards: [
      { id: "c1", icon: "Question", label: "Why Makkah holds a unique place in Islam." },
      { id: "c2", icon: "MoonStars", label: "What pilgrims may experience upon arrival." },
      { id: "c3", icon: "BookOpen", label: "How to approach the sacred city with humility and gratitude." },
      { id: "c4", icon: "Heart", label: "How to prepare your heart before entering Masjid al-Haram." },
      { id: "c5", icon: "Star", label: "What comes next in the Hajj journey." },
    ]},
    { type: "narrativeText", title: "Overview", icon: "BookOpen", paragraphs: [
      "For many pilgrims, arriving in Makkah is the realization of a lifelong dream. It is the birthplace of Prophet Muhammad ﷺ, the home of the Ka'bah, and the direction Muslims face in prayer every day.",
      "For centuries, believers have journeyed from every corner of the world to reach this sacred city. As you arrive, take a moment to appreciate where you are. Before any ritual begins, simply recognize the blessing of having answered Allah's invitation.",
    ]},
    { type: "narrativeText", title: "Why it Matters", icon: "Heart", paragraphs: [
      "Makkah is not sacred because of its buildings or landscape. It is sacred because Allah chose it as the home of His Sacred House and made it the destination of Hajj.",
      "Every step taken within this city reminds the pilgrim that they are walking where prophets, companions, scholars, and millions of believers have walked before them. Arriving in Makkah is a reminder that Allah's promise to gather believers continues in every generation.",
    ]},
    { type: "narrativeText", title: "Historical Context", icon: "BookOpen", paragraphs: [
      "Makkah has been a place of worship since the time of Prophet Ibrahim (AS) and Prophet Isma'il (AS), who rebuilt the Ka'bah by Allah's command.",
      "It later became the birthplace of Prophet Muhammad ﷺ, through whom the rites of Hajj were restored to their original purpose: the worship of Allah alone. Today, Makkah remains the spiritual heart of the Muslim world.",
    ]},
    { type: "numberedSteps", title: "Your First Moments in Makkah", steps: [
      { heading: "Pause", body: "Let the arrival settle. Before thinking about the next ritual, pause and thank Allah for bringing you safely to this blessed place. Many people spend years hoping to reach Makkah. Your presence here is itself a blessing." },
      { heading: "Remember Your Intention", body: "Renew your intention for Hajj. The excitement of arriving can easily become focused on the place itself. Instead, let every moment remind you that your purpose is worship." },
      { heading: "Be Patient", body: "Expect crowds and delays. The city will be busy. There may be crowds, delays, and moments of fatigue. Approach each experience with patience and gratitude, remembering that millions of others share this same journey." },
      { heading: "Prepare for the Ka'bah", body: "Calm your heart before the next stage. Soon, you will enter Masjid al-Haram and see the Ka'bah for the first time. Use these moments to slow down, make du'a, and prepare yourself for that unforgettable sight." },
      { heading: "Stay Present", body: "Notice the blessing without rushing past it. The first moments in Makkah can easily become a checklist of logistics. Give yourself space to recognize the spiritual significance of having reached the sacred city." },
    ]},
    { type: "cardList", title: "Things to Remember", cards: [
      { id: "t1", icon: "Star", label: "Makkah is the holiest city in Islam." },
      { id: "t2", icon: "Heart", label: "Arriving is a blessing in itself." },
      { id: "t3", icon: "MoonStars", label: "Renew your intention before beginning the rituals." },
      { id: "t4", icon: "Question", label: "Be patient and grateful." },
      { id: "t5", icon: "BookOpen", label: "Prepare your heart before entering the Sacred Mosque." },
      { id: "t6", icon: "ListChecks", label: "Do not let logistics completely crowd out gratitude." },
      { id: "t7", icon: "Heart", label: "Remember that other pilgrims are sharing the same sacred journey." },
      { id: "t8", icon: "Star", label: "The next stage brings you face to face with the Ka'bah." },
    ]},
    { type: "cardList", title: "Key Takeaways", cards: [
      { id: "k1", icon: "Star", label: "Makkah is the destination of Hajj because Allah made it sacred." },
      { id: "k2", icon: "BookOpen", label: "Countless generations have journeyed here before you." },
      { id: "k3", icon: "Heart", label: "Arrival is a moment for gratitude before action." },
      { id: "k4", icon: "Question", label: "Patience is part of the experience of entering a crowded sacred city." },
      { id: "k5", icon: "MoonStars", label: "Your purpose remains worship, even amid travel and logistics." },
      { id: "k6", icon: "ListChecks", label: "The next stage will reveal the Ka'bah and prepare you for Tawaf." },
    ]},
    { type: "insight", title: "Insight", text: "Many pilgrims remember the exact moment they first entered Makkah. Not because of what they saw, but because of what they felt. Years of hope, preparation, and prayer suddenly become reality. Sometimes the most meaningful act is simply to pause, breathe, and thank Allah." },
    { type: "cardList", title: "Practice", cards: [
      { id: "p1", icon: "Star", label: "Before travelling, spend a few moments visualizing your arrival." },
      { id: "p2", icon: "Heart", label: "Picture yourself entering Makkah with humility, gratitude, and calm." },
      { id: "p3", icon: "BookOpen", label: "Write down three things you would want to remember in your first moments there." },
      { id: "p4", icon: "Question", label: "Think about how you will respond if the journey includes delays, crowds, or fatigue." },
      { id: "p5", icon: "MoonStars", label: "Prepare a short personal du'a of gratitude for reaching the Sacred City." },
      { id: "p6", icon: "ListChecks", label: "Remind yourself that the goal is worship, not simply reaching a destination." },
    ]},
    { type: "qaCardList", title: "Common Questions", cards: [
      { id: "q1", question: "Should I rush to the Ka'bah as soon as I arrive?", answer: "Many pilgrims are eager to begin immediately, but taking a few moments to compose yourself, renew your intention, and approach the Sacred Mosque calmly can make the experience more meaningful." },
      { id: "q2", question: "Why is Makkah considered sacred?", answer: "Allah chose Makkah as the location of the Ka'bah and designated it as the destination of Hajj and the direction of prayer for Muslims around the world." },
      { id: "q3", question: "Is every part of Hajj performed in Makkah?", answer: "No. While many important rites begin in Makkah, Hajj also takes pilgrims to Mina, Arafah, Muzdalifah, and other sacred locations during the days of pilgrimage." },
      { id: "q4", question: "Why is arriving in Makkah itself meaningful?", answer: "For many pilgrims, arrival represents the realization of years of hope, preparation, and prayer and the blessing of answering Allah's call." },
      { id: "q5", question: "What should I focus on when I first arrive?", answer: "Focus on gratitude, humility, remembrance of Allah, and renewing your intention for Hajj." },
      { id: "q6", question: "How should I handle crowds and delays?", answer: "Approach them with patience and gratitude. Crowds, delays, and fatigue are part of the reality of a city receiving millions of pilgrims." },
      { id: "q7", question: "Should I focus on the city itself or on worship?", answer: "Let the city remind you of worship rather than becoming the focus itself. Makkah is sacred because Allah chose it for His Sacred House and the pilgrimage." },
      { id: "q8", question: "What should I do before entering Masjid al-Haram?", answer: "Calm your heart, renew your intention, and prepare yourself for seeing the Ka'bah." },
      { id: "q9", question: "Why does the lesson ask me to pause?", answer: "Pausing creates space to recognize the blessing of reaching a place that many Muslims spend years hoping to visit." },
      { id: "q10", question: "Is it normal to feel overwhelmed when arriving?", answer: "Years of hope, preparation, and prayer can suddenly become reality. Your response may include gratitude, excitement, quiet reflection, or other emotions." },
      { id: "q11", question: "What if my arrival does not feel as emotional as I expected?", answer: "There is no prescribed emotional response. The important focus is gratitude, humility, and worship rather than trying to create a particular feeling." },
      { id: "q12", question: "What comes next?", answer: "The next stage brings you to the Ka'bah and prepares you for the next part of the pilgrimage." },
    ]},
    { type: "narrativeText", title: "Scholar Notes", icon: "BookOpen", paragraphs: [
      "Throughout Islamic history, scholars have encouraged pilgrims to enter Makkah with humility, gratitude, and remembrance of Allah.",
      "While anticipation naturally builds as the Ka'bah draws near, preparing the heart before entering Masjid al-Haram helps ensure that the first moments in the Sacred Mosque are filled with presence rather than distraction.",
    ]},
    { type: "companionTool", title: "Discover Makkah", description: "Explore the history of Makkah, Masjid al-Haram, the Ka'bah, sacred boundaries (Haram), important landmarks, and etiquette within the Sacred Mosque.", ctaLabel: "Open Sacred Places", ctaScreen: "SacredPlaces", ctaMode: "root" },
    { type: "narrativeText", title: "References", icon: "BookOpen", paragraphs: [
      "Qur'an — Surah Aal 'Imran (3:96–97)",
      "Qur'an — Surah Al-Hajj (22:26–29)",
      "Qur'an — Surah Al-Baqarah (2:125)",
      "Hadith — Sahih al-Bukhari, Book of Hajj",
      "Hadith — Sahih Muslim, Book of Hajj",
      "Classical Scholarship — Imam an-Nawawi; Ibn Qudamah; Ibn Hajar al-'Asqalani",
      "Contemporary Guidance — Saudi Ministry of Hajj & Umrah; General Authority for the Care of the Two Holy Mosques",
    ]},
  ],
};
