import hajjLesson4Cover from "../../assets/lesson_images/hajj_lesson4.png";

export const LESSON_HAJJ_04 = {
  id: "hajj-04",
  guide: "hajj",
  lessonNumber: 4,
  totalLessons: 16,
  title: "The Talbiyah",
  blocks: [
    { type: "cover", image: hajjLesson4Cover, lessonBadge: "LESSON 4 OF 16", title: "The Talbiyah", subtitle: "Learn the meaning of the Talbiyah—the timeless declaration every pilgrim recites throughout Hajj.", readingMinutes: 6 },
    { type: "cardList", title: "After This Lesson You'll Understand", cards: [
      { id: "c1", icon: "Question", label: "What the Talbiyah is." },
      { id: "c2", icon: "MoonStars", label: "When it is recited." },
      { id: "c3", icon: "BookOpen", label: "What its words mean." },
      { id: "c4", icon: "Star", label: "Why it is central to the experience of Hajj." },
      { id: "c5", icon: "Heart", label: "How to make its meaning part of your worship." },
    ]},
    { type: "narrativeText", title: "Overview", icon: "BookOpen", paragraphs: [
      "After entering Ihram, pilgrims begin reciting the Talbiyah. For centuries, these words have echoed through the valleys surrounding Makkah as millions of Muslims answered Allah's call to pilgrimage.",
      "The Talbiyah is more than a phrase to memorize. It is a declaration of faith, obedience, gratitude, and complete devotion to Allah. Every repetition reminds the pilgrim why they have come.",
    ]},
    { type: "narrativeText", title: "Why it Matters", icon: "Heart", paragraphs: [
      "When you recite the Talbiyah, you are responding to the invitation Allah gave through Prophet Ibrahim (AS): \"And proclaim the pilgrimage to mankind...\"",
      "The Talbiyah is your answer. Every pilgrim—regardless of language, nationality, or background—recites the same words, joining generations of believers who have answered this sacred call.",
    ]},
    { type: "narrativeText", title: "The Words", icon: "BookOpen", paragraphs: [
      "Labbayka Allahumma labbayk. Labbayka la sharika laka labbayk. Innal hamda wan-ni'mata laka wal-mulk. La sharika lak.",
      "\"Here I am, O Allah, here I am. Here I am. You have no partner. Here I am. Surely all praise, every blessing, and all sovereignty belong to You. You have no partner.\"",
    ]},
    { type: "narrativeText", title: "Understanding Its Meaning", icon: "Star", paragraphs: [
      "\"Here I am\" is a response to Allah's invitation: you come willingly and sincerely. \"You have no partner\" is an affirmation of Tawhid—the oneness of Allah—and reminds the pilgrim that every act of Hajj is performed for Him alone.",
      "\"All praise belongs to You\" recognizes that everything we possess is from Allah and that pilgrimage is an act of gratitude before it is an act of movement.",
    ]},
    { type: "narrativeText", title: "When Is It Recited?", icon: "ListChecks", paragraphs: [
      "Pilgrims begin reciting the Talbiyah after entering Ihram. It is repeated often throughout the journey until the appropriate point in the rites of Hajj, keeping the heart focused on Allah.",
    ]},
    { type: "numberedSteps", title: "Step-by-Step", steps: [
      { heading: "Learn the Words", body: "Prepare before you travel. Spend time learning the Arabic pronunciation and the meaning of each sentence so the Talbiyah feels familiar when you enter Ihram." },
      { heading: "Understand the Response", body: "Hear \"Here I am\" as a commitment. The words are a response to Allah's call. Let them carry sincerity rather than becoming a phrase repeated without awareness." },
      { heading: "Remember Tawhid", body: "Let \"You have no partner\" re-center you. Every act of Hajj is performed for Allah alone." },
      { heading: "Remember Gratitude", body: "Notice what you are affirming. The Talbiyah declares that praise, blessing, and sovereignty belong to Allah." },
      { heading: "Repeat with Presence", body: "Use repetition to renew your intention. Each repetition can bring your heart back to the reason you came for Hajj." },
      { heading: "Join the Call", body: "Notice the voices around you. Pilgrims from different languages and backgrounds recite the same declaration, joining generations of believers." },
    ]},
    { type: "cardList", title: "Things to Remember", cards: [
      { id: "t1", icon: "Star", label: "The Talbiyah begins after entering Ihram." },
      { id: "t2", icon: "BookOpen", label: "It is recited frequently during Hajj." },
      { id: "t3", icon: "Heart", label: "Reflect on its meaning—not just its words." },
      { id: "t4", icon: "MoonStars", label: "Let it renew your intention throughout the pilgrimage." },
      { id: "t5", icon: "Question", label: "The prescribed wording is recited in Arabic." },
      { id: "t6", icon: "ListChecks", label: "Understanding the translation helps deepen your reflection." },
      { id: "t7", icon: "Star", label: "The Talbiyah is a declaration of Tawhid, gratitude, and submission." },
      { id: "t8", icon: "Heart", label: "Millions of pilgrims share the same declaration." },
    ]},
    { type: "cardList", title: "Key Takeaways", cards: [
      { id: "k1", icon: "Star", label: "The Talbiyah is the pilgrim's response to Allah's call." },
      { id: "k2", icon: "MoonStars", label: "It proclaims Allah's oneness." },
      { id: "k3", icon: "Heart", label: "It expresses gratitude and submission." },
      { id: "k4", icon: "BookOpen", label: "It accompanies the pilgrim throughout the early stages of Hajj." },
      { id: "k5", icon: "Question", label: "Its repetition is meant to keep the heart connected to Allah." },
      { id: "k6", icon: "ListChecks", label: "Learning it before travel can make recitation more confident and meaningful." },
    ]},
    { type: "insight", title: "Insight", text: "Millions of voices. One declaration. For a few extraordinary days, differences of language disappear. The same words rise from every direction, reminding each pilgrim that they are part of something far greater than themselves." },
    { type: "cardList", title: "Practice", cards: [
      { id: "p1", icon: "BookOpen", label: "Learn the Talbiyah before travelling." },
      { id: "p2", icon: "Star", label: "Practice its pronunciation slowly rather than relying only on memorization." },
      { id: "p3", icon: "Heart", label: "Learn the meaning of every sentence." },
      { id: "p4", icon: "MoonStars", label: "Listen to a native Arabic recitation." },
      { id: "p5", icon: "ListChecks", label: "Practice phrase-by-phrase with the translation." },
      { id: "p6", icon: "Question", label: "When you recite it during Hajj, use each repetition as a reminder of your intention." },
    ]},
    { type: "qaCardList", title: "Common Questions", cards: [
      { id: "q1", question: "Do I have to memorize the Talbiyah before Hajj?", answer: "It is highly recommended to learn it before travelling so you can recite it confidently and reflect on its meaning throughout the pilgrimage." },
      { id: "q2", question: "Can I recite the Talbiyah in my own language?", answer: "The prescribed Talbiyah is recited in Arabic. Learning its meaning in your own language helps deepen understanding while preserving the wording taught by the Prophet ﷺ." },
      { id: "q3", question: "Why is it repeated so often?", answer: "Its repetition keeps the heart connected to Allah and continually renews the pilgrim's intention during the journey." },
      { id: "q4", question: "When do I begin reciting it?", answer: "Pilgrims begin reciting the Talbiyah after entering Ihram." },
      { id: "q5", question: "How long do I continue reciting it?", answer: "It is repeated often throughout the journey until the appropriate point in the rites of Hajj." },
      { id: "q6", question: "What does \"Labbayka\" mean?", answer: "\"Here I am\"—a response to Allah's invitation and a statement of willingness and sincerity." },
      { id: "q7", question: "What does \"la sharika lak\" mean?", answer: "It means that Allah has no partner, affirming Tawhid and the fact that Hajj is performed for Allah alone." },
      { id: "q8", question: "Why does the Talbiyah mention praise and blessing?", answer: "It acknowledges that all praise and every blessing belong to Allah and frames pilgrimage as an act of gratitude." },
      { id: "q9", question: "Is the Talbiyah just something to memorize?", answer: "No. It is a declaration of faith, obedience, gratitude, and complete devotion." },
      { id: "q10", question: "Why do pilgrims recite the same words?", answer: "The same declaration unites pilgrims regardless of language, nationality, or background and connects them with generations of believers." },
      { id: "q11", question: "How can I avoid reciting it mechanically?", answer: "Learn the meaning of each phrase and use each repetition as a conscious reminder of why you came to Hajj." },
      { id: "q12", question: "What is the best way to prepare?", answer: "Practice pronunciation, learn the meaning, listen to a native recitation, and become comfortable with the full Talbiyah before travelling." },
    ]},
    { type: "narrativeText", title: "Scholar Notes", icon: "BookOpen", paragraphs: [
      "The Talbiyah is among the most recognizable features of Hajj. Scholars have long encouraged pilgrims to recite it frequently, with presence of heart and reflection on its meaning.",
      "Its purpose is not repetition for its own sake, but continual remembrance of Allah and reaffirmation of sincere worship.",
    ]},
    { type: "narrativeText", title: "References", icon: "BookOpen", paragraphs: [
      "Qur'an — Surah Al-Hajj (22:27)",
      "Qur'an — Surah Al-Baqarah (2:196–203)",
      "Hadith — Sahih al-Bukhari, Book of Hajj",
      "Hadith — Sahih Muslim, Book of Hajj",
      "Classical Scholarship — Imam an-Nawawi; Ibn Hajar al-'Asqalani; Ibn Qudamah",
      "Contemporary Guidance — Saudi Ministry of Hajj & Umrah; General Authority for the Care of the Two Holy Mosques",
    ]},
  ],
};
