import umrahLesson1Cover from "../../assets/lesson_images/umrah_lesson1.png";

export const LESSON_UMRAH_01 = {
  id: "umrah-01",
  guide: "umrah",
  lessonNumber: 1,
  totalLessons: 10,
  title: "Welcome to Umrah",
  blocks: [
    { type: "cover", image: umrahLesson1Cover, lessonBadge: "LESSON 1 OF 10", title: "Welcome to Umrah", subtitle: "Discover what Umrah is, why Muslims perform it, and what you'll learn throughout this guide.", readingMinutes: 4 },
    { type: "cardList", title: "After This Lesson You'll Understand", cards: [
      { id: "c1", icon: "Question", label: "What Umrah is" },
      { id: "c2", icon: "MoonStars", label: "Why Muslims perform Umrah" },
      { id: "c3", icon: "BookOpen", label: "What to expect throughout this learning guide." },
    ]},
    { type: "narrativeText", title: "Overview", image: "kaaba", paragraphs: [
      "Umrah is a pilgrimage to the Sacred House of Allah (the Ka'bah) in Makkah.",
      "Unlike Hajj, it can be performed at almost any time of the year.",
      "This guide helps learners understand each part of Umrah before travelling so they arrive informed, confident and spiritually prepared.",
    ]},
    { type: "narrativeText", title: "Why it Matters", icon: "Heart", paragraphs: [
      "Umrah is an act of worship performed solely for Allah.",
      "It is an opportunity to seek forgiveness, strengthen faith and follow the example of the Prophet Muhammad ﷺ while remembering the legacy of Prophet Ibrahim (AS) and Hajar (AS).",
    ]},
    { type: "narrativeText", title: "Historical Context", icon: "BookOpen", paragraphs: [
      "The rituals trace back to Prophet Ibrahim (AS), Hajar (AS), and the rebuilding\nof the Ka'bah.",
      "The Prophet Muhammad ﷺ demonstrated how Muslims perform Umrah, preserving it for future generations.",
    ]},
    { type: "bulletList", title: "What You'll Learn\nin this Umrah Guide", icon: "Star", bullets: ["Preparation", "Ihram", "Talbiyah", "Tawaf", "Maqam Ibrahim", "Zamzam", "Sa'i", "Halq/Taqsir", "Completing Umrah"] },
    { type: "qaCardList", title: "Things to Remember", closing: "You don't need to know everything before you begin. You just need to begin learning.", cards: [
      { id: "t0", question: "Umrah is an act of worship.", answer: "Its purpose is to draw closer to Allah, seek forgiveness, and strengthen your faith." },
      { id: "t1", question: "Umrah can be performed throughout the year.", answer: "Unlike Hajj, it is not restricted to a specific set of days." },
      { id: "t2", question: "Understanding comes before memorization.", answer: "You don't need to memorize everything before beginning your journey." },
      { id: "t3", question: "The rituals have a history.", answer: "Umrah connects you to the legacy of Ibrahim (AS), Hajar (AS), and the Prophet Muhammad ﷺ." },
      { id: "t4", question: "Preparation is part of the journey.", answer: "Learning what to expect can help you approach the pilgrimage with greater confidence and peace of mind." },
      { id: "t5", question: "You will learn the journey step by step.", answer: "The guide will take you through preparation, Ihram, Talbiyah, Tawaf, Zamzam, Sa'i, Halq/Taqsir, and completing Umrah." },
      { id: "t6", question: "You don't have to learn everything at once.", answer: "Move through the lessons at your own pace and return to sections whenever you need a refresher." },
      { id: "t7", question: "Your questions are part of learning.", answer: "Use My Notes to save questions, reminders, and things you want to revisit." },
      { id: "t8", question: "There are legitimate differences of scholarly opinion.", answer: "When you encounter an issue where scholars differ, learn the reasoning and follow the guidance of a trusted scholar or local community." },
      { id: "t9", question: "The goal is to arrive prepared, not perfect.", answer: "Let your preparation create space for worship, reflection, and presence rather than adding pressure to your journey." },
    ]},
    { type: "qaCardList", title: "Common Questions", cards: [
      { id: "q1", question: "What exactly is Umrah?", answer: "Umrah is a pilgrimage to the Sacred House of Allah in Makkah. It includes a series of acts of worship centered around the Ka'bah and the sacred sites connected to the pilgrimage." },
      { id: "q2", question: "When can I perform Umrah?", answer: "Unlike Hajj, Umrah can be performed throughout the year. You can therefore choose a time that works for your circumstances and travel plans." },
      { id: "q3", question: "Is Umrah obligatory?", answer: "Scholars have differed on this question. Some hold that Umrah is obligatory once in a lifetime for those who are able, while others consider it a highly recommended Sunnah. Follow the guidance of a trusted scholar or qualified local authority." },
      { id: "q4", question: "How is Umrah different from Hajj?", answer: "Hajj is the major pilgrimage and has specific dates during Dhul Hijjah. Umrah can be performed throughout the year and has a shorter sequence of rites." },
      { id: "q5", question: "What are the main steps of Umrah?", answer: "The guide will walk you through preparation, Ihram, Talbiyah, Tawaf, Maqam Ibrahim, Zamzam, Sa'i, Halq or Taqsir, and completing Umrah." },
      { id: "q6", question: "Do I need to memorize all the duas before I go?", answer: "No. Understanding the meaning and purpose of the worship is more important than trying to memorize everything at once. You can also use Safar to keep the duas and reminders you want with you." },
      { id: "q7", question: "Do I need to know Arabic to perform Umrah?", answer: "You do not need to be fluent in Arabic. Learning the key phrases and duas used during Umrah can help you participate more confidently, but understanding what you are saying is also valuable." },
      { id: "q8", question: "What is Ihram?", answer: "Ihram refers to the sacred state a pilgrim enters in preparation for performing Umrah, along with the specific requirements and restrictions associated with that state. The guide will explain this in detail in the Ihram lesson." },
      { id: "q9", question: "What is the Talbiyah?", answer: "The Talbiyah is the declaration pilgrims recite after entering Ihram, expressing their response to Allah's call. You will learn its meaning and when it is recited in the Talbiyah lesson." },
      { id: "q10", question: "What is Tawaf?", answer: "Tawaf is the act of circling the Ka'bah seven times as an act of worship. The guide will explain how to prepare for Tawaf and what to focus on while performing it." },
      { id: "q11", question: "What is Sa'i?", answer: "Sa'i is walking between Safa and Marwah, commemorating the actions of Hajar (AS). It is one of the central rites of Umrah and will be covered later in the guide." },
      { id: "q12", question: "Why are Ibrahim (AS) and Hajar (AS) connected to Umrah?", answer: "Many of the rituals and sacred places associated with pilgrimage connect us to the legacy of Prophet Ibrahim (AS), Hajar (AS), and their family. Their story helps us understand the deeper meaning behind the rites." },
      { id: "q13", question: "Do I need to be in perfect spiritual shape before performing Umrah?", answer: "No. Umrah itself is an opportunity to turn toward Allah, seek forgiveness, strengthen faith, and grow in worship. Preparation is about arriving with intention and understanding—not being spiritually \"perfect.\"" },
      { id: "q14", question: "What should I prepare before travelling?", answer: "Preparation includes both practical and spiritual preparation. You'll want to understand the rites, organize your travel needs, learn what you'll need for Ihram, and prepare yourself mentally and spiritually for the journey." },
      { id: "q15", question: "Do I need to memorize the entire sequence before I travel?", answer: "No. The purpose of this guide is to help you understand the journey before you go. You can learn at your own pace and return to individual lessons as often as needed." },
    ]},
    { type: "narrativeText", title: "Scholar Notes", icon: "BookOpen", paragraphs: [
      { heading: "Different scholarly opinions" },
      "Scholars have differed over the ruling of Umrah. Some scholars hold that it is obligatory once in a lifetime for a person who is able to perform it, while others consider it a highly recommended Sunnah.",
      "Both positions are well-established within Islamic scholarship. This is one reason Safar does not present the question as having a single undisputed answer.",
      { heading: "What should I do?" },
      "Follow the guidance of a trusted scholar or qualified local community who can advise you according to your circumstances and the scholarly tradition you follow.",
      { heading: "A useful principle for this guide" },
      "You may encounter differences of opinion as you learn about Umrah. Not every difference means that one side is simply \"right\" and the other is \"wrong.\" Where established scholarly opinions differ, Safar will help you understand the difference without unnecessarily turning the learning experience into a debate.",
    ]},
    { type: "cardList", title: "Key Takeaways", cards: [
      { id: "k1", icon: "Heart", label: "Umrah is a pilgrimage of worship that draws Muslims closer to Allah." },
      { id: "k2", icon: "MoonStars", label: "It can be performed throughout the year." },
      { id: "k3", icon: "BookOpen", label: "Its rituals connect us to the legacy of Ibrahim (AS), Hajar (AS), and the Prophet Muhammad ﷺ." },
      { id: "k4", icon: "Star", label: "This guide helps you prepare with understanding, confidence, and spiritual awareness." },
    ]},
    { type: "narrativeText", title: "References", icon: "BookOpen", paragraphs: [
      "Qur'an: 2:125–128, 2:158, 22:26–29",
      "Hadith: Sahih al-Bukhari & Sahih Muslim (Books of Hajj)",
      "Classical scholarship and contemporary Hajj guidance.",
    ]},
  ],
};
