import hajjLesson6Cover from "../../assets/lesson_images/hajj_lesson6.png";

export const LESSON_HAJJ_06 = {
  id: "hajj-06",
  guide: "hajj",
  lessonNumber: 6,
  totalLessons: 16,
  title: "Seeing the Ka'bah",
  blocks: [
    { type: "cover", image: hajjLesson6Cover, lessonBadge: "LESSON 6 OF 16", title: "Seeing the Ka'bah", subtitle: "Discover the significance of the Ka'bah and prepare for one of the most unforgettable moments of your pilgrimage.", readingMinutes: 6 },
    { type: "cardList", title: "After This Lesson You'll Understand", cards: [
      { id: "c1", icon: "Question", label: "The significance of the Ka'bah in Islam." },
      { id: "c2", icon: "Heart", label: "Why seeing it for the first time can be so meaningful." },
      { id: "c3", icon: "MoonStars", label: "How to approach this moment with humility and gratitude." },
      { id: "c4", icon: "BookOpen", label: "Why the Ka'bah is not worshipped." },
      { id: "c5", icon: "Star", label: "What comes next before beginning Tawaf." },
    ]},
    { type: "moment", image: hajjLesson6Cover, quote: "Every prayer you've ever performed has faced this direction." },
    { type: "narrativeText", title: "Overview", icon: "BookOpen", paragraphs: [
      "For many pilgrims, seeing the Ka'bah for the first time is the moment they have imagined for years. It is the Sacred House built by Prophet Ibrahim (AS) and Prophet Isma'il (AS) by Allah's command, and it serves as the qiblah—the direction Muslims face in prayer throughout the world.",
      "Although the Ka'bah is made of stone, its significance comes entirely from the honor Allah has bestowed upon it. It is not worshipped. Rather, it is the focal point that unites Muslims in the worship of Allah alone.",
    ]},
    { type: "narrativeText", title: "Why it Matters", icon: "Heart", paragraphs: [
      "Every day, millions of Muslims turn toward the Ka'bah in prayer. For perhaps the first time in your life, you are now standing before the very place you've faced countless times.",
      "The Ka'bah reminds believers of Allah's unity, the legacy of Prophet Ibrahim (AS), and the continuity of Islamic worship across generations.",
    ]},
    { type: "narrativeText", title: "Historical Context", icon: "BookOpen", paragraphs: [
      "The Qur'an tells us that Prophet Ibrahim (AS) and his son Isma'il (AS) raised the foundations of the Ka'bah while praying that Allah would accept their efforts.",
      "Since then, it has remained the spiritual center of Islamic worship. Throughout history, countless believers have stood before it with the same hopes, fears, prayers, and gratitude that pilgrims carry today.",
    ]},
    { type: "numberedSteps", title: "Preparing for Your First Sight", steps: [
      { heading: "Pause", body: "Resist the urge to rush. Take a moment simply to absorb what is before you. This is a moment many Muslims dream about for a lifetime." },
      { heading: "Remember Allah", body: "Let the sight point beyond the building. Your focus is not the building itself. Your focus is the One who made this place sacred. Let the sight of the Ka'bah draw your heart toward Allah." },
      { heading: "Reflect", body: "Recognize the chain of believers. You have joined an unbroken chain of believers stretching back to Prophet Ibrahim (AS), Prophet Muhammad ﷺ, and every pilgrim who has answered Allah's call." },
      { heading: "Prepare for Tawaf", body: "Settle your heart before you move. Soon you will begin circling the Ka'bah. Before you move, settle your heart and renew your intention." },
      { heading: "Allow Your Response", body: "Do not compare your emotions. Some pilgrims feel overwhelming joy, others quiet gratitude, and some simply stand in silence. There is no need to force a particular response." },
      { heading: "Remember the Purpose", body: "Keep the focus on Allah. The Ka'bah is honored because Allah made it sacred; it is not an object of worship. Let the sight strengthen your remembrance of Allah rather than becoming an end in itself." },
    ]},
    { type: "cardList", title: "Things to Remember", cards: [
      { id: "t1", icon: "Star", label: "The Ka'bah is the qiblah for Muslims worldwide." },
      { id: "t2", icon: "Heart", label: "It is honored because Allah made it sacred." },
      { id: "t3", icon: "Question", label: "Worship is directed to Allah alone." },
      { id: "t4", icon: "MoonStars", label: "Your first sight is a moment for gratitude and reflection." },
      { id: "t5", icon: "BookOpen", label: "Your emotional response may be different from another pilgrim's." },
      { id: "t6", icon: "Star", label: "The Ka'bah represents unity in worship." },
      { id: "t7", icon: "Heart", label: "Remember the legacy of Prophet Ibrahim (AS) and Isma'il (AS)." },
      { id: "t8", icon: "ListChecks", label: "Prepare your heart before beginning Tawaf." },
      { id: "t9", icon: "Question", label: "Tawaf begins in the next stage." },
    ]},
    { type: "cardList", title: "Key Takeaways", cards: [
      { id: "k1", icon: "Star", label: "The Ka'bah is the spiritual center of Islamic worship." },
      { id: "k2", icon: "MoonStars", label: "It symbolizes unity, not an object of worship." },
      { id: "k3", icon: "Heart", label: "Seeing it for the first time can be deeply emotional." },
      { id: "k4", icon: "Question", label: "The building itself is not the object of worship; Allah alone is worshipped." },
      { id: "k5", icon: "BookOpen", label: "Every prayer you've performed facing the qiblah has pointed you toward this place." },
      { id: "k6", icon: "Star", label: "Your first sight can become a moment of gratitude, reflection, and renewed intention." },
      { id: "k7", icon: "ListChecks", label: "The next stage begins teaching the rite of Tawaf." },
    ]},
    { type: "insight", title: "Insight", text: "Every prayer you've ever performed has faced this direction. Now, for the first time, your eyes meet the direction your heart has faced all along. Many pilgrims find that words become difficult. Some smile. Some stand silently. Some weep. Each response is different—but all are reminders of Allah's immense blessing." },
    { type: "cardList", title: "Practice", cards: [
      { id: "p1", icon: "BookOpen", label: "Learn the history of the Ka'bah." },
      { id: "p2", icon: "Heart", label: "Reflect on the story of Prophet Ibrahim (AS) and Prophet Isma'il (AS)." },
      { id: "p3", icon: "MoonStars", label: "Spend a few minutes after each prayer imagining your first moments inside Masjid al-Haram." },
      { id: "p4", icon: "Star", label: "Write a personal prayer you would want to make when you first see the Ka'bah." },
      { id: "p5", icon: "Question", label: "Remind yourself that there is no required emotional performance—sincerity matters more than intensity." },
      { id: "p6", icon: "ListChecks", label: "Review the distinction between facing the Ka'bah in prayer and worshipping Allah alone." },
      { id: "p7", icon: "BookOpen", label: "Prepare mentally for the transition from this reflective moment into Tawaf." },
    ]},
    { type: "qaCardList", title: "Common Questions", cards: [
      { id: "q1", question: "Is the Ka'bah worshipped?", answer: "No. Muslims worship Allah alone. The Ka'bah is the qiblah that unites Muslims in prayer and serves as the focal point of Tawaf." },
      { id: "q2", question: "Why is the Ka'bah covered with a black cloth?", answer: "It is covered with the Kiswah, a beautifully embroidered cloth that is replaced periodically as part of the care given to the Sacred House." },
      { id: "q3", question: "Should I expect an emotional reaction?", answer: "Every pilgrim's experience is unique. Some feel overwhelming joy, others quiet gratitude, and some simply stand in silent reflection. There is no 'correct' emotional response." },
      { id: "q4", question: "Why do Muslims face the Ka'bah in prayer?", answer: "The Ka'bah is the qiblah—the direction Muslims face in prayer—and a unifying focal point for Muslim worship." },
      { id: "q5", question: "Who built the Ka'bah?", answer: "Prophet Ibrahim (AS) and his son Isma'il (AS) raised its foundations by Allah's command." },
      { id: "q6", question: "Why is the Ka'bah important if Muslims do not worship it?", answer: "Its significance comes from the honor Allah has bestowed upon it. It unites Muslims in worship of Allah alone." },
      { id: "q7", question: "What should I focus on when I first see it?", answer: "Focus on Allah, gratitude, remembrance, and the privilege of being present at the Sacred House." },
      { id: "q8", question: "What if I don't cry or feel overwhelmed?", answer: "That does not mean the moment is less meaningful. Every pilgrim's experience is unique and there is no 'correct' emotional response." },
      { id: "q9", question: "Should I rush to begin Tawaf?", answer: "Pause, absorb the moment, remember Allah, reflect, and settle your heart before beginning Tawaf." },
      { id: "q10", question: "What does the Ka'bah represent?", answer: "It represents unity in worship, the legacy of Prophet Ibrahim (AS), and the continuity of Islamic worship across generations." },
      { id: "q11", question: "What should I learn before seeing the Ka'bah?", answer: "Learn its history, reflect on Prophet Ibrahim (AS) and Isma'il (AS), and prepare a personal prayer for that moment." },
      { id: "q12", question: "What comes after seeing the Ka'bah?", answer: "The next stage begins teaching Tawaf, the act of circling the Ka'bah." },
    ]},
    { type: "narrativeText", title: "Scholar Notes", icon: "BookOpen", paragraphs: [
      "Scholars have long encouraged pilgrims to approach the Ka'bah with humility, gratitude, and remembrance of Allah.",
      "While the first sight of the Sacred House is deeply moving for many, its greatest significance lies in what it represents: devotion to Allah and the legacy of worship established by Prophet Ibrahim (AS).",
    ]},
    { type: "companionTool", title: "Explore the Ka'bah", description: "Learn about the history of the Ka'bah, the Kiswah, the Black Stone (al-Hajar al-Aswad), the Multazam, the Door of the Ka'bah, the Mizab, the Hatim (Hijr Isma'il), and Maqam Ibrahim.", ctaLabel: "Open Sacred Places", ctaScreen: "SacredPlaces", ctaMode: "root" },
    { type: "narrativeText", title: "References", icon: "BookOpen", paragraphs: [
      "Qur'an — Surah Al-Baqarah (2:125–127)",
      "Qur'an — Surah Aal 'Imran (3:96–97)",
      "Qur'an — Surah Al-Hajj (22:26–29)",
      "Hadith — Sahih al-Bukhari, Book of Hajj",
      "Hadith — Sahih Muslim, Book of Hajj",
      "Classical Scholarship — Imam an-Nawawi; Ibn Hajar al-'Asqalani; Ibn Qudamah",
      "Contemporary Guidance — Saudi Ministry of Hajj & Umrah; General Authority for the Care of the Two Holy Mosques",
    ]},
  ],
};
