import hajjLesson10Cover from "../../assets/lesson_images/hajj_lesson10.png";

export const LESSON_HAJJ_10 = {
  id: "hajj-10",
  guide: "hajj",
  lessonNumber: 10,
  totalLessons: 16,
  title: "The Day of Arafah",
  blocks: [
    { type: "cover", image: hajjLesson10Cover, lessonBadge: "LESSON 10 OF 16", title: "The Day of Arafah", subtitle: "Understand why the standing at Arafah is the heart of Hajj — and how to make the most of this sacred day.", readingMinutes: 11 },
    { type: "cardList", title: "After This Lesson You'll Understand", cards: [
      { id: "c1", icon: "Question", label: "Why Arafah is called the heart of Hajj." },
      { id: "c2", icon: "Heart", label: "What Wuquf (the standing) is and why it is essential." },
      { id: "c3", icon: "MoonStars", label: "How to spend the hours of Arafah in worship." },
      { id: "c4", icon: "BookOpen", label: "The significance of the Plain of Arafah and Jabal ar-Rahmah." },
      { id: "c5", icon: "Star", label: "What happens if a pilgrim misses Arafah." },
    ]},
    { type: "narrativeText", title: "Overview", icon: "BookOpen", paragraphs: [
      "The Day of Arafah is the 9th of Dhul Hijjah. It is the most sacred day of the Hajj pilgrimage and one of the most sacred days of the Islamic year. The Prophet ﷺ said: 'Hajj is Arafah.'",
      "On this day, pilgrims stand on the Plain of Arafah—a vast open expanse approximately 20 kilometres from Makkah—from midday until sunset, engaged in prayer, remembrance, and supplication.",
    ]},
    { type: "narrativeText", title: "Why Arafah is the Heart of Hajj", icon: "Star", paragraphs: [
      "The standing at Arafah (Wuquf) is the single most important act of Hajj. If a pilgrim misses it, their Hajj is invalid and cannot be compensated by any other act. Every other rite of Hajj can be made up or expiated—Arafah cannot.",
      "The day is a foretaste of the Day of Judgment: millions of people gathered in one place, wearing simple white garments, equal before Allah, each calling upon their Lord. The scales are tipped, sins are forgiven, and Allah descends to the lowest heaven to answer the du'as of those who stand there.",
    ]},
    { type: "narrativeText", title: "The Plain of Arafah", icon: "Heart", paragraphs: [
      "The Plain of Arafah is a broad, open valley. At its center stands Jabal ar-Rahmah—the Mount of Mercy—where the Prophet ﷺ delivered his Farewell Sermon on this very day, addressing more than 100,000 companions.",
      "You do not need to climb Jabal ar-Rahmah. The Wuquf is valid anywhere within the boundaries of Arafah. What matters is being present, in Ihram, with intention, for the prescribed time.",
    ]},
    { type: "narrativeText", title: "How Allah Responds to This Day", icon: "MoonStars", paragraphs: [
      "The Prophet ﷺ said: 'There is no day on which Allah frees more of His slaves from the Fire than the Day of Arafah. He draws near and then boasts about them to His angels, saying: What do these people want?' (Sahih Muslim)",
      "This hadith is among the most hopeful in all of Islamic tradition. Arafah is not just a day of ritual—it is a day of divine response. Every sincere prayer made at Arafah is heard.",
    ]},
    { type: "narrativeText", title: "The Farewell Sermon", icon: "BookOpen", paragraphs: [
      "The Prophet ﷺ delivered his final khutbah to the ummah on the Day of Arafah during his only Hajj. He addressed the rights of people, the sanctity of life and property, the equality of all believers, and the importance of holding fast to the Qur'an and Sunnah.",
      "His final question to the gathered believers was: 'Have I conveyed the message?' They answered: 'Yes.' He then said: 'O Allah, bear witness.' Standing at Arafah, you stand on that same plain, receiving the same message.",
    ]},
    { type: "numberedSteps", title: "How to Spend the Day of Arafah", steps: [
      { heading: "Arrive at Arafah After Fajr", body: "Depart from Mina after Fajr on the 9th of Dhul Hijjah and travel to Arafah. You must arrive before sunset to count as having performed Wuquf." },
      { heading: "Pray Dhuhr and Asr Together", body: "At Arafah, Dhuhr and Asr are combined and shortened: both prayed as two rak'ahs each at Dhuhr time. Follow the imam or pray independently if you are not with a congregation." },
      { heading: "Begin the Standing (Wuquf)", body: "From midday, stand (or sit) in a state of Wuquf. Face the qiblah. Engage your heart completely. Recite the Talbiyah, make du'a, read Qur'an, and engage in dhikr." },
      { heading: "Fill Every Moment with Du'a", body: "The best du'a on this day—and the best du'a of all time—is: 'La ilaha illallah wahdahu la sharika lah, lahu'l-mulku wa lahu'l-hamd, wa huwa 'ala kulli shay'in qadir.' Make it often and make personal du'a freely." },
      { heading: "Do Not Leave Before Sunset", body: "Wuquf continues until after sunset. Leaving before sunset renders Hajj incomplete. Stay until the signal to depart for Muzdalifah." },
      { heading: "Depart for Muzdalifah After Sunset", body: "After sunset, depart calmly for Muzdalifah. The Prophet ﷺ departed with dignity and calm, not in a rush. Pray Maghrib and Isha combined at Muzdalifah." },
    ]},
    { type: "cardList", title: "Things to Remember", cards: [
      { id: "t1", icon: "Star", label: "'Hajj is Arafah.' Missing it invalidates Hajj." },
      { id: "t2", icon: "Heart", label: "Wuquf is valid anywhere within the boundaries of Arafah." },
      { id: "t3", icon: "MoonStars", label: "Dhuhr and Asr are combined and shortened at Arafah." },
      { id: "t4", icon: "Question", label: "Do not leave Arafah before sunset." },
      { id: "t5", icon: "BookOpen", label: "The best du'a: 'La ilaha illallah wahdahu la sharika lah...'" },
      { id: "t6", icon: "Star", label: "Allah draws near and responds to du'a on this day." },
      { id: "t7", icon: "ListChecks", label: "You do not need to climb Jabal ar-Rahmah." },
      { id: "t8", icon: "Heart", label: "Depart for Muzdalifah after sunset, calmly." },
      { id: "t9", icon: "MoonStars", label: "Maghrib and Isha are combined at Muzdalifah." },
      { id: "t10", icon: "Star", label: "Observe the Talbiyah throughout the standing." },
    ]},
    { type: "cardList", title: "Key Takeaways", cards: [
      { id: "k1", icon: "Star", label: "Arafah is the heart of Hajj — the most important act." },
      { id: "k2", icon: "Heart", label: "Allah frees more people from the Fire on this day than any other." },
      { id: "k3", icon: "BookOpen", label: "The Prophet ﷺ delivered the Farewell Sermon here." },
      { id: "k4", icon: "Question", label: "Wuquf must extend from midday until after sunset." },
      { id: "k5", icon: "MoonStars", label: "Every sincere du'a at Arafah is heard." },
      { id: "k6", icon: "ListChecks", label: "After sunset, proceed to Muzdalifah for combined Maghrib and Isha." },
    ]},
    { type: "insight", title: "A Moment to Notice", text: "At Arafah, pilgrims from every nation, every language, and every background stand together in white, facing the same qiblah, calling upon the same Lord. There is no visible difference between them. This is what Islam looks like when you step back far enough to see it whole." },
    { type: "insight", title: "Insight", text: "The Prophet ﷺ was asked about fasting on the Day of Arafah. He said it expiates the sins of the previous year and the coming year. This day carries mercy for those at Hajj and those who are not—a gift that extends far beyond the plain itself." },
    { type: "insight", title: "Reflection", text: "You are given hours at Arafah to ask Allah for anything. What would you ask for? And what would you want to say to Allah before you left the plain?" },
    { type: "cardList", title: "Practice", cards: [
      { id: "p1", icon: "Star", label: "Memorise the best du'a of Arafah: 'La ilaha illallah wahdahu la sharika lah, lahu'l-mulku wa lahu'l-hamd, wa huwa 'ala kulli shay'in qadir.'" },
      { id: "p2", icon: "Heart", label: "Read the text of the Prophet's ﷺ Farewell Sermon." },
      { id: "p3", icon: "BookOpen", label: "Learn the boundaries of Arafah and what constitutes valid Wuquf." },
      { id: "p4", icon: "MoonStars", label: "Prepare a personal du'a list for Arafah — for yourself, your family, and the ummah." },
      { id: "p5", icon: "Question", label: "Understand the ruling on combining and shortening prayers at Arafah." },
      { id: "p6", icon: "ListChecks", label: "Fast on the Day of Arafah if you are not performing Hajj this year." },
      { id: "p7", icon: "Star", label: "Understand what Muzdalifah is and what happens there after leaving Arafah." },
      { id: "p8", icon: "Heart", label: "Read the hadith about what Allah says about the people of Arafah on this day." },
      { id: "p9", icon: "BookOpen", label: "Review the schedule: arrive at Arafah, combine Dhuhr/Asr, stand until sunset, depart." },
      { id: "p10", icon: "MoonStars", label: "Reflect on what you would ask Allah if you knew He was listening — because He is." },
    ]},
    { type: "qaCardList", title: "Common Questions", cards: [
      { id: "q1", question: "Is the standing at Arafah obligatory?", answer: "Yes. Wuquf at Arafah is a pillar of Hajj. Missing it invalidates the entire Hajj, and it cannot be compensated by any other act." },
      { id: "q2", question: "When does Wuquf begin and end?", answer: "Wuquf begins from midday on the 9th of Dhul Hijjah and continues until sunset. Pilgrims must be present for at least part of this time." },
      { id: "q3", question: "Must I stand the entire time, or can I sit?", answer: "You may sit, stand, or rest. The word 'standing' refers to being present at Arafah, not literally remaining on your feet." },
      { id: "q4", question: "Do I need to climb Jabal ar-Rahmah?", answer: "No. The Wuquf is valid anywhere within the boundaries of Arafah. Climbing the mountain is not required." },
      { id: "q5", question: "What is the best du'a to make at Arafah?", answer: "The Prophet ﷺ said: 'The best du'a is the du'a of the Day of Arafah, and the best that I and the prophets before me have said is: La ilaha illallah wahdahu la sharika lah, lahu'l-mulku wa lahu'l-hamd, wa huwa 'ala kulli shay'in qadir.'" },
      { id: "q6", question: "How are prayers performed at Arafah?", answer: "Dhuhr and Asr are combined and shortened at Dhuhr time: both are prayed as two rak'ahs each. Follow the imam or pray independently." },
      { id: "q7", question: "What if I arrive at Arafah after sunset?", answer: "According to many scholars, Wuquf is still valid if you arrive before Fajr of the 10th. However, arriving before sunset is essential to follow the Sunnah." },
      { id: "q8", question: "What happens if I leave Arafah before sunset?", answer: "Pilgrims who stand at Arafah during the day should remain there until after sunset before departing for Muzdalifah. Leaving before sunset without returning is considered a violation according to the majority of scholars and generally requires a compensatory sacrifice (dam)." },
      { id: "q9", question: "What is Jabal ar-Rahmah?", answer: "It is the Mount of Mercy within the Plain of Arafah, where the Prophet ﷺ delivered his Farewell Sermon. It holds historical and spiritual significance but climbing it is not required." },
      { id: "q10", question: "What does the hadith say Allah does on the Day of Arafah?", answer: "The Prophet ﷺ said: 'There is no day on which Allah frees more of His slaves from the Fire than the Day of Arafah. He draws near and then boasts about them to His angels.' (Sahih Muslim)" },
      { id: "q11", question: "Where do pilgrims go after leaving Arafah?", answer: "Pilgrims travel to Muzdalifah, where they pray Maghrib and Isha combined. They collect pebbles there and spend the night before returning to Mina on Eid day." },
      { id: "q12", question: "Can I fast on the Day of Arafah if I am not performing Hajj?", answer: "Yes. The Prophet ﷺ said fasting on the Day of Arafah expiates the sins of the previous year and the coming year. It is one of the most recommended voluntary fasts in Islam." },
    ]},
    { type: "narrativeText", title: "Scholar Notes", icon: "BookOpen", paragraphs: [
      "There is scholarly consensus that Wuquf at Arafah is the most important pillar of Hajj. Ibn Qudamah, Imam an-Nawawi, and Ibn Hajar al-'Asqalani all emphasised that anyone who fails to be present at Arafah during the prescribed time has missed Hajj entirely.",
      "Scholars also noted that the Day of Arafah is not only for pilgrims: fasting it expiates two years of sins for all Muslims, and the angels witness the du'as of those present at Arafah in a way unlike any other day of the year.",
      "The Prophet ﷺ remained at Arafah until after sunset before departing for Muzdalifah. Based on this practice, the majority of scholars consider remaining until sunset obligatory for those who were present during the day. If a pilgrim leaves before sunset and does not return to remain at Arafah into the night, the majority require a dam. The details differ among the schools of Islamic jurisprudence, so pilgrims should follow the guidance of their qualified scholar or Hajj group.",
    ]},
    { type: "narrativeText", title: "References", icon: "BookOpen", paragraphs: [
      "Qur'an — Surah Al-Baqarah (2:198–203)",
      "Qur'an — Surah Al-Ma'idah (5:3) — revealed on the Day of Arafah",
      "Hadith — Sahih Muslim, Book of Hajj: 'Hajj is Arafah'",
      "Hadith — Sahih Muslim: Allah freeing people from the Fire on the Day of Arafah",
      "Hadith — Tirmidhi: the best du'a of the Day of Arafah",
      "Hadith — Sahih Muslim: fasting on the Day of Arafah",
      "Classical Scholarship — Imam an-Nawawi; Ibn Qudamah; Ibn Hajar al-'Asqalani",
      "Contemporary Guidance — Saudi Ministry of Hajj & Umrah; General Authority for the Care of the Two Holy Mosques",
    ]},
    { type: "insight", title: "My Notes Prompt", icon: "NotePencil", text: "Imagine you are standing on the Plain of Arafah as the sun begins to set. You have hours left to make du'a. What would you say to Allah? Write the prayer you would want to carry into that moment." },
  ],
};
