import umrahLesson2Cover from "../../assets/lesson_images/umrah_lesson2.png";

export const LESSON_UMRAH_02 = {
  id: "umrah-02",
  guide: "umrah",
  lessonNumber: 2,
  totalLessons: 10,
  title: "Preparing for Umrah",
  blocks: [
    { type: "cover", image: umrahLesson2Cover, lessonBadge: "LESSON 2 OF 10", title: "Preparing for Umrah", subtitle: "Learn how to prepare spiritually and practically so you can begin your pilgrimage with confidence and peace of mind.", readingMinutes: 5 },
    { type: "cardList", title: "After This Lesson You'll Understand", cards: [
      { id: "c1", icon: "Question", label: "Why preparation is an important part of Umrah." },
      { id: "c2", icon: "MoonStars", label: "How to prepare spiritually and practically." },
      { id: "c3", icon: "BookOpen", label: "What to do before you leave home." },
    ]},
    { type: "narrativeText", title: "Overview", icon: "BookOpen", paragraphs: [
      "Preparing for Umrah begins long before you arrive in Makkah. Muslims prepare both practically and spiritually so they can focus on worship once their journey begins.",
      "Good preparation does not mean having every detail under control; it means taking reasonable steps to reduce avoidable distractions and arriving with a clear intention.",
      "This includes learning the journey, organizing travel essentials, preparing physically, and making time for repentance, du'a and reflection.",
    ]},
    { type: "narrativeText", title: "Why it Matters", icon: "Heart", paragraphs: [
      "Preparation helps reduce stress, strengthens intention and allows you to approach Umrah with sincerity and peace of mind.",
      "When practical matters are handled ahead of time, you create more room for worship and reflection. Spiritual preparation is equally important: renew your intention, seek forgiveness, and think about what you hope to take away from the journey.",
      "The goal is not perfection. It is to arrive prepared enough that your attention can turn toward Allah.",
    ]},
    { type: "narrativeText", title: "Historical Context", icon: "BookOpen", paragraphs: [
      "Pilgrims have always prepared carefully before embarking on this sacred journey. While travel is easier today, preparation remains an important part of the pilgrimage.",
      "The outward details have changed with time, but the need to prepare the heart, understand the rites, and make arrangements for the journey remains.",
    ]},
    { type: "narrativeText", title: "How to Prepare", icon: "ListChecks", paragraphs: [
      "Prepare in three connected areas: spiritually, practically and for travel.",
      "Start with your intention and learning, then work through forgiveness, documents, physical readiness, packing and essential duas. Finally, prepare your heart for the experience itself.",
      "Work through these steps gradually rather than trying to do everything at once.",
    ]},
    { type: "numberedSteps", title: "Step-by-Step", steps: [
      { heading: "Renew your intention (Niyyah)", body: "Remind yourself why you are making this journey. Begin by renewing your intention for Umrah and asking Allah to accept your worship. Your intention gives meaning to the practical work that follows." },
      { heading: "Learn before you travel", body: "Understand the journey before you arrive. Learn the sequence of Umrah and become familiar with the major stages. You do not need to master everything immediately; focus on understanding what happens and why." },
      { heading: "Seek forgiveness", body: "Prepare inwardly through repentance. Use the time before travel to seek Allah's forgiveness, make du'a, and resolve to leave behind habits or distractions that you hope to change." },
      { heading: "Organize your documents", body: "Handle important practical details early. Gather and organize your passport, visa and other travel documents so they are easy to access. Early organization can prevent avoidable stress close to departure." },
      { heading: "Prepare physically", body: "Give your body reasonable preparation. Think ahead about rest, hydration, clothing, footwear and the amount of walking involved. Preparing within your own circumstances can make the journey more comfortable." },
      { heading: "Pack thoughtfully", body: "Bring what you need without unnecessary clutter. Pack around the actual needs of the journey. Consider clothing, personal items, medications, worship essentials and documents, and use a checklist to reduce last-minute decisions." },
      { heading: "Learn the essential duas", body: "Focus on understanding rather than memorizing everything. Learn the key duas and phrases you expect to use, along with their meanings. You do not need to memorize every dua before travelling." },
      { heading: "Prepare your heart", body: "Make space for worship, patience and reflection. Think about what you hope to ask Allah for, what you hope to leave behind, and how you want the experience to shape you. Leave room for patience when plans change." },
    ]},
    { type: "duaList", title: "Recommended Duas", duas: ["A safe journey", "Ease in worship", "Acceptance", "Forgiveness", "Health", "Protection"], ctaLabel: "Explore Umrah Duas", ctaScreen: "PilgrimageDuas", ctaMode: "root", ctaParams: { mode: "umrah" } },
    { type: "cardList", title: "Things to Remember", cards: [
      { id: "t1", icon: "Star", label: "Preparation begins before you travel." },
      { id: "t2", icon: "Heart", label: "Prepare your heart as well as your suitcase." },
      { id: "t3", icon: "MoonStars", label: "Renew your intention regularly." },
      { id: "t4", icon: "BookOpen", label: "Learn before you arrive." },
      { id: "t5", icon: "ListChecks", label: "Take care of practical details early." },
      { id: "t6", icon: "Star", label: "Prepare physically." },
      { id: "t7", icon: "Question", label: "Don't overwhelm yourself with memorization." },
      { id: "t8", icon: "Heart", label: "Aim to be prepared, not perfect." },
    ]},
    { type: "qaCardList", title: "Common Questions", cards: [
      { id: "q1", question: "When should I start preparing for Umrah?", answer: "If possible, begin several weeks or months before your journey. Starting early gives you time to learn the rituals, organize travel details, and prepare spiritually without feeling rushed." },
      { id: "q2", question: "What should I prepare spiritually?", answer: "Begin by renewing your intention, seeking forgiveness, making du'a, and learning about the journey ahead. Preparation is not only about knowing what to pack—it is about preparing yourself for an act of worship." },
      { id: "q3", question: "Do I need to memorize all the duas before Umrah?", answer: "No. You do not need to memorize every dua before travelling. Focus first on understanding the meaning and purpose of the worship. You can continue learning throughout your preparation." },
      { id: "q4", question: "What should I learn before I travel?", answer: "Learn the overall sequence of Umrah and become familiar with the major stages: Ihram, Talbiyah, Tawaf, Zamzam, Sa'i, and Halq or Taqsir." },
      { id: "q5", question: "What documents should I organize before leaving?", answer: "Make sure your important travel and pilgrimage documents are organized and accessible. Safar's preparation checklists can help you keep track of what you need before departure." },
      { id: "q6", question: "Do I need to prepare physically for Umrah?", answer: "Some physical preparation can make the journey more comfortable. Think ahead about rest, hydration, appropriate footwear and clothing, and how you will manage walking and crowded places." },
      { id: "q7", question: "What should I pack for Umrah?", answer: "Pack thoughtfully rather than simply packing more. Consider the clothing, personal items, medications, worship essentials, and travel documents you will actually need." },
      { id: "q8", question: "What if I don't know much about the rituals yet?", answer: "That's exactly why preparation matters. You don't need to know everything before you leave. Work through the guide step by step and focus on understanding the purpose of each part of the journey." },
      { id: "q9", question: "What if I make a mistake during Umrah?", answer: "Don't let the fear of making a mistake prevent you from learning. When you are unsure about an important issue, ask a trusted scholar or qualified guide rather than guessing." },
      { id: "q10", question: "How can I prepare my family or travel group?", answer: "Talk together about the journey before you leave. Make sure everyone understands the basic plan, knows where important documents are, and has a way to stay connected if the group becomes separated." },
      { id: "q11", question: "How do I prepare if I feel overwhelmed?", answer: "Break preparation into small steps. Learn one part of the journey at a time and organize one category of practical tasks at a time." },
      { id: "q12", question: "What is the most important thing to remember before leaving?", answer: "You are preparing for an act of worship, not simply a trip. Practical planning helps create the space for you to focus on your relationship with Allah once the journey begins." },
    ]},
    { type: "narrativeText", title: "Scholar Notes", icon: "BookOpen", paragraphs: [
      { heading: "A balanced approach to preparation" },
      "Islamic guidance encourages preparation for pilgrimage both inwardly and outwardly. Outward preparation includes taking care of the practical matters that allow you to travel and perform your worship responsibly.",
      "Inward preparation includes sincere intention, repentance, remembrance of Allah, and preparing yourself mentally and spiritually for the journey.",
      "Neither should replace the other. Practical preparation reduces avoidable distractions, while spiritual preparation helps ensure that the journey remains centered on worship.",
      { heading: "A useful principle: prepare carefully, then place your trust in Allah." },
    ]},
    { type: "cardList", title: "Key Takeaways", cards: [
      { id: "k1", icon: "Star", label: "Preparation begins before you leave home." },
      { id: "k2", icon: "Heart", label: "Spiritual preparation is as important as practical preparation." },
      { id: "k3", icon: "MoonStars", label: "A sincere intention gives purpose to everything that follows." },
      { id: "k4", icon: "BookOpen", label: "Learning the journey beforehand can reduce uncertainty and help you remain present." },
      { id: "k5", icon: "Heart", label: "Good preparation creates space for worship rather than adding pressure to it." },
      { id: "k6", icon: "Star", label: "You don't need to be perfect—you need to be prepared, sincere, and willing to learn." },
    ]},
    { type: "companionTool", title: "Use Safar's Checklists", description: "Use Safar's Checklists feature for pre-populated and custom checklists as you prepare for your journey.", ctaLabel: "Open Checklists", ctaScreen: "Checklists", ctaTab: "Plan" },
    { type: "narrativeText", title: "References", icon: "BookOpen", paragraphs: [
      "Qur'an: 2:197, 22:27–29",
      "Hadith: Sahih al-Bukhari & Sahih Muslim (Books of Hajj)",
    ]},
  ],
};
